### ISSUE TITLE
Panic when backing up to Amazon S3

### ISSUE THREAD

**Issue by gabesullice** [restic/restic#1023]
## Output of `restic version`
```sh
restic 0.6.1 (v0.6.1-56-g0b55be25)
compiled with go1.8.3 on linux/amd64
```

## How did you start restic exactly? (Include the complete command line)
```sh
$ cat $HOME/scripts/restic-backup.sh
#!/bin/bash

RESTIC_REPOSITORY="s3:s3.amazonaws.com/<mybucket>" \
AWS_ACCESS_KEY_ID="<my_key_id>" \
AWS_SECRET_ACCESS_KEY="<my_access_key>" \
restic -p /home/gabe/restic-backup-password.txt \
  --exclude='/**/.data/mysql' \
  --exclude='/**/node_modules' \
  --exclude='/**/sites/*/files' \
  --exclude='*.tgz' \
  --exclude='*.tar.gz' \
  --exclude='*.sql.gz' \
  --exclude='*.sql' \
  --exclude='/**/.data/mysql' \
  backup \
  /home/gabe/projects/aten \
  /home/gabe/projects/contrib \
  /home/gabe/projects/github.com \
  /home/gabe/projects/bitbucket.org \
  /home/gabe/projects/drupal.org \
  /home/gabe/projects/go/src \
  /home/gabe/projects/presentations \
  /home/gabe/projects/devops \
  /home/gabe/Documents

$ sudo ./scripts/restic-backup.sh
```

## What backend/server/service did you use?
Amazon S3

## Expected behavior
I expected my backup to succeed? :man_shrugging: I know that's not incredibly useful. Happy to answer more questions though.

## Actual behavior
```sh
scan [/home/gabe/projects/aten /home/gabe/projects/contrib /home/gabe/projects/github.com /home/gabe/projects/bitbucket.org /home/gabe/projects/drupal.org /home/gabe/projects/go/src /home/gabe/projects/presentations /home/gabe/projects/devops /home/gabe/Documents]
scanned 172600 directories, 620951 files in 1:50
panic: client.PutObject: Put https://s3-us-west-2.amazonaws.com/<mybucket>/restic/data/02bda62992525e37cd5a0f7920a5be25b916d541beeacd928b6b6be0147f6f9c: dial tcp: lookup s3-us-west-2.amazonaws.com on [2601:282:204:3d83:6a1:51ff:fee7:cc58]:53: read udp [2601:282:204:3d83:931b:80a:708a:3256]:48578->[2601:282:204:3d83:6a1:51ff:fee7:cc58]:53: i/o timeout

goroutine 52544 [running]:
restic/archiver.(*Archiver).saveChunk(0xc420337950, 0xc194a0, 0xc420018428, 0x0, 0x2e4d8, 0x1, 0xc421cca000, 0x2e4d8, 0x80000, 0xc420434840, ...)
	src/restic/archiver/archiver.go:164 +0x293
created by restic/archiver.(*Archiver).SaveFile
	src/restic/archiver/archiver.go:238 +0x3a4
```

## Steps to reproduce the behavior
I'm not sure if there's anything especially unique or complicated that I'm doing to get this bug to come up. This happens every time I run the backup script above.

## Do you have any idea what may have caused this?
The only thing that I _might_ have done that was strange is killed the backup script with `^C` multiple times as I was attempting to get all my `--exclude`s correct. Perhaps this corrupted my bucket in some way? Sorry, wish I knew more about this to give a better bug report.

**Comment by fd0** [comment]
Thanks for the report, and for providing all the details in the template. Could you please run the backup again, and when the error occurs then dump the currently active connections with `netstat -an | egrep :(443|53) > /tmp/netstat`? Then either paste this file here (maybe redacted) or have a look at the number of connections to s3 (in state ESTABLISHED or TIME_WAIT). Are there a lot?

**Comment by fd0** [comment]
The issue should be fixed in #1025, could you please give the code in the branch `fix-1013` a try?

**Comment by gabesullice** [comment]
Here is the output of netstat _pre_ `fix-1013`.  I am running with `fix-1013` now and will report back on whether the issue is resolved.

```
tcp        0      0 192.168.1.6:37224       50.31.166.176:443       ESTABLISHED
tcp        0 309313 192.168.1.6:57440       54.231.185.20:443       FIN_WAIT1  
tcp        0      0 192.168.1.6:44730       34.208.216.244:443      ESTABLISHED
tcp        0      0 192.168.1.6:35882       54.231.184.208:443      TIME_WAIT  
tcp        0    748 192.168.1.6:55146       216.58.217.46:443       ESTABLISHED
tcp        0      0 192.168.1.6:55112       216.58.217.46:443       ESTABLISHED
tcp        0 765047 192.168.1.6:34116       52.218.144.44:443       FIN_WAIT1  
tcp        0 227689 192.168.1.6:57400       54.231.185.20:443       FIN_WAIT1  
tcp        0      0 192.168.1.6:41236       172.217.12.14:443       ESTABLISHED
tcp        0      0 192.168.1.6:49680       54.230.120.123:443      ESTABLISHED
tcp        0      0 192.168.1.6:44808       54.239.30.25:443        ESTABLISHED
tcp        0      0 192.168.1.6:48026       104.16.112.18:443       ESTABLISHED
tcp        0      0 192.168.1.6:48872       192.30.253.125:443      ESTABLISHED
tcp        0 254897 192.168.1.6:53302       54.231.176.164:443      FIN_WAIT1  
tcp        0 297857 192.168.1.6:57410       54.231.185.20:443       FIN_WAIT1  
tcp        0      0 192.168.1.6:41206       172.217.12.14:443       ESTABLISHED
tcp        0    573 192.168.1.6:60984       52.218.128.132:443      FIN_WAIT1  
tcp        0 736049 192.168.1.6:34832       54.231.185.32:443       FIN_WAIT1  
tcp        0      0 192.168.1.6:48612       192.30.253.125:443      ESTABLISHED
tcp        0      0 192.168.1.6:35884       54.231.184.208:443      TIME_WAIT  
tcp        0 625688 192.168.1.6:35880       54.231.184.208:443      FIN_WAIT1  
tcp        0 279241 192.168.1.6:57412       54.231.185.20:443       FIN_WAIT1  
tcp        0 273513 192.168.1.6:43206       52.218.128.4:443        FIN_WAIT1  
tcp        0      0 192.168.1.6:48884       192.30.253.125:443      ESTABLISHED
tcp        0      0 192.168.1.6:43208       52.218.128.4:443        TIME_WAIT  
tcp        0     32 192.168.1.6:54790       54.231.169.32:443       FIN_WAIT1  
tcp        0 884977 192.168.1.6:34114       52.218.144.44:443       FIN_WAIT1  
tcp        0      0 192.168.1.6:42278       216.58.194.78:443       ESTABLISHED
tcp        0 231985 192.168.1.6:43212       52.218.128.4:443        FIN_WAIT1  
tcp        0      0 192.168.1.6:44264       198.252.206.25:443      ESTABLISHED
tcp        0      0 192.168.1.6:51920       34.223.242.85:443       ESTABLISHED
tcp        0 571369 192.168.1.6:57416       54.231.185.20:443       FIN_WAIT1  
tcp        0      0 192.168.1.6:47980       52.35.123.126:443       ESTABLISHED
tcp        0  79716 192.168.1.6:60978       52.218.128.132:443      FIN_WAIT1  
tcp        0      0 192.168.1.6:48032       104.16.112.18:443       ESTABLISHED
tcp        0      0 192.168.1.6:35886       54.231.184.208:443      TIME_WAIT  
tcp        0      0 192.168.1.6:51922       34.223.242.85:443       ESTABLISHED
tcp        0 1018153 192.168.1.6:34834       54.231.185.32:443       FIN_WAIT1  
tcp        0 180433 192.168.1.6:57434       54.231.185.20:443       FIN_WAIT1  
tcp        0 204777 192.168.1.6:57402       54.231.185.20:443       FIN_WAIT1  
tcp        0      0 192.168.1.6:48030       104.16.112.18:443       ESTABLISHED
tcp        0      0 192.168.1.6:41216       172.217.12.14:443       ESTABLISHED
tcp        0      0 192.168.1.6:47824       172.226.254.211:443     ESTABLISHED
tcp        0      0 192.168.1.6:49862       151.101.193.69:443      ESTABLISHED
tcp        0      0 192.168.1.6:48028       104.16.112.18:443       ESTABLISHED
tcp        0      0 192.168.1.6:41740       52.25.204.247:443       ESTABLISHED
tcp        0 276377 192.168.1.6:57408       54.231.185.20:443       FIN_WAIT1  
tcp        0      0 192.168.1.6:44608       34.208.216.244:443      ESTABLISHED
tcp        0      0 192.168.1.6:60980       52.218.128.132:443      TIME_WAIT  
tcp        0      0 192.168.1.6:43768       52.39.120.161:443       ESTABLISHED
tcp        0      0 192.168.1.6:53308       54.231.176.164:443      TIME_WAIT  
tcp        0      0 192.168.1.6:53306       54.231.176.164:443      TIME_WAIT  
tcp        0 497398 192.168.1.6:54862       52.218.160.76:443       FIN_WAIT1  
tcp        0 219097 192.168.1.6:57420       54.231.185.20:443       FIN_WAIT1  
tcp        0 242009 192.168.1.6:57432       54.231.185.20:443       FIN_WAIT1  
tcp        0      0 192.168.1.6:48034       104.16.112.18:443       ESTABLISHED
tcp6       0      0 2601:282:204:3d83:37748 2001:1838:2001:e::1:443 TIME_WAIT  
tcp6       0      0 2601:282:204:3d83:56462 2a00:1450:400e:800::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:34888 2607:f8b0:400e:c04::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:35770 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:35894 2607:f8b0:4005:80a::443 TIME_WAIT  
tcp6       0      0 2601:282:204:3d83:36168 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:45136 2607:f8b0:4005:80a::443 TIME_WAIT  
tcp6       0      0 2601:282:204:3d83:35924 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:36178 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:34848 2607:f8b0:400e:c04::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:33808 2607:f8b0:400a:809::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:37750 2001:1838:2001:e::1:443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:36816 2607:f8b0:4005:804::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:44798 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:34840 2607:f8b0:400e:c04::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:46098 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:46100 2607:f8b0:4005:80a::443 ESTABLISHED
udp        0      0 0.0.0.0:5353            0.0.0.0:*                          
udp        0      0 0.0.0.0:5353            0.0.0.0:*                          
udp        0      0 192.168.1.6:44837       192.168.1.1:53          ESTABLISHED
udp6       0      0 :::5353                 :::*                               
udp6       0      0 :::5353                 :::*                               
udp6       0      0 :::5353                 :::*                               
udp6       0      0 :::5353                 :::*                               
udp6       0      0 :::5353                 :::*                               
udp6       0      0 :::5353                 :::*                               
```

**Comment by gabesullice** [comment]
`fix-1013` did not resolve the issue. Here is the output of netstat with that version:

```
tcp        0      0 192.168.1.6:37224       50.31.166.176:443       ESTABLISHED
tcp        0      0 192.168.1.6:44730       34.208.216.244:443      ESTABLISHED
tcp        0 1111233 192.168.1.6:33052       54.231.176.208:443      FIN_WAIT1  
tcp        0      0 192.168.1.6:57790       52.218.160.52:443       TIME_WAIT  
tcp        0      0 192.168.1.6:57778       52.218.160.52:443       TIME_WAIT  
tcp        0      0 192.168.1.6:44078       151.101.68.133:443      TIME_WAIT  
tcp        0 292129 192.168.1.6:41664       54.231.168.212:443      FIN_WAIT1  
tcp        0      0 192.168.1.6:57780       52.218.160.52:443       TIME_WAIT  
tcp        0      0 192.168.1.6:55476       216.58.217.46:443       ESTABLISHED
tcp        0      0 192.168.1.6:57786       52.218.160.52:443       TIME_WAIT  
tcp        0 830561 192.168.1.6:33064       54.231.176.208:443      FIN_WAIT1  
tcp        0      0 192.168.1.6:48872       192.30.253.125:443      ESTABLISHED
tcp        0      0 192.168.1.6:58938       192.30.253.116:443      TIME_WAIT  
tcp        0 339385 192.168.1.6:33048       54.231.176.208:443      FIN_WAIT1  
tcp        0      0 192.168.1.6:44076       151.101.68.133:443      TIME_WAIT  
tcp        0      0 192.168.1.6:48612       192.30.253.125:443      ESTABLISHED
tcp        0 165266 192.168.1.6:33050       54.231.176.208:443      FIN_WAIT1  
tcp        0      0 192.168.1.6:44068       151.101.68.133:443      ESTABLISHED
tcp        0      0 192.168.1.6:48884       192.30.253.125:443      ESTABLISHED
tcp        0      0 192.168.1.6:44070       151.101.68.133:443      ESTABLISHED
tcp        0      0 192.168.1.6:44264       198.252.206.25:443      ESTABLISHED
tcp        0      0 192.168.1.6:51920       34.223.242.85:443       ESTABLISHED
tcp        0      0 192.168.1.6:47980       52.35.123.126:443       ESTABLISHED
tcp        0 297857 192.168.1.6:55570       52.218.208.88:443       FIN_WAIT1  
tcp        0      0 192.168.1.6:51922       34.223.242.85:443       ESTABLISHED
tcp        0 462537 192.168.1.6:36020       52.218.160.44:443       FIN_WAIT1  
tcp        0      1 192.168.1.6:42924       54.231.168.164:443      FIN_WAIT1  
tcp        0 443921 192.168.1.6:55568       52.218.208.88:443       FIN_WAIT1  
tcp        0      0 192.168.1.6:40374       192.30.253.113:443      TIME_WAIT  
tcp        0 307881 192.168.1.6:55566       52.218.208.88:443       FIN_WAIT1  
tcp        0      0 192.168.1.6:41740       52.25.204.247:443       ESTABLISHED
tcp        0      0 192.168.1.6:44072       151.101.68.133:443      ESTABLISHED
tcp        0      0 192.168.1.6:50782       54.230.120.123:443      ESTABLISHED
tcp        0      0 192.168.1.6:44608       34.208.216.244:443      ESTABLISHED
tcp        0      0 192.168.1.6:57782       52.218.160.52:443       TIME_WAIT  
tcp        0 667313 192.168.1.6:33066       54.231.176.208:443      FIN_WAIT1  
tcp        0      0 192.168.1.6:43768       52.39.120.161:443       ESTABLISHED
tcp6       0      0 2601:282:204:3d83:36598 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:46524 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:45284 2607:f8b0:4001:c0c::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:45850 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:45874 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:36512 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:36596 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:36014 2607:f8b0:400e:c04::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:36480 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:36496 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:36486 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:36010 2607:f8b0:400e:c04::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:46522 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       0      0 2601:282:204:3d83:36494 2607:f8b0:4005:80a::443 ESTABLISHED
tcp6       1      1 2601:282:204:3d83:36478 2607:f8b0:4005:80a::443 CLOSING    
udp        0      0 0.0.0.0:5353            0.0.0.0:*                          
udp        0      0 0.0.0.0:5353            0.0.0.0:*                          
udp6       0      0 :::5353                 :::*                               
udp6       0      0 :::5353                 :::*                               
udp6       0      0 :::5353                 :::*                               
udp6       0      0 :::5353                 :::*                               
udp6       0      0 :::5353                 :::*                               
udp6       0      0 :::5353                 :::*                               
```

**Comment by fd0** [comment]
Hm, interesting. From the error message it looks like restic (via the `minio-go` s3 client library we're using) tries to open a new connection to s3 but the hostname lookup fails. This may be the case when too many file descriptors are used, we've seen that before but never really figured out the cause...

I have two suggestions on what you could try:
 * Lower the number of concurrent connections to s3, use the code in the branch `fix-1013` and run `restic -o s3.connections=2 backup ...`.  Let's see if that is of any help.
 * Try building restic with `go run build.go --enable-cgo`. This (among others) uses the libc's DNS resolver instead of the internal Go resolver.

I'm looking forward to your feedback!

**Comment by gabesullice** [comment]
When I run with the `s3.connections` option, I get: `option s3.connections is not known`

I'm wondering if I'm actually compiling the right version, I have `fix-1013` checked out, but I still get:

```sh
[0] gabe ~ $ restic version
restic 0.6.1 (v0.6.1-22-ga0eebf85)
compiled with go1.8.3 on linux/amd64
```

I'm compiling like so:

```sh
[0] gabe restic:fix $ pwd
/home/gabe/projects/go/src/github.com/restic/restic
[0] gabe restic:fix $ git branch
* fix-1013
  master
[0] gabe restic:fix $ go run build.go
```

I'm running a backup with `--enable-cgo` and will report when done.

**Comment by fd0** [comment]
Something is off here, that's a very old commit. Could you please run: `git fetch origin` and `git reset --hard origin/fix-1013`?

**Comment by gabesullice** [comment]
Okay, ran fetch and reset hard.

```
restic 0.6.1 (v0.6.1-69-g422c0dfb)
compiled with go1.8.3 on linux/amd64
```

Without `s3.connections=2`:

```
scan [/home/gabe/Documents /home/gabe/projects/github.com /home/gabe/projects/aten /home/gabe/projects/contrib /home/gabe/projects/bitbucket.org /home/gabe/projects/drupal.org /home/gabe/projects/go/src /home/gabe/projects/presentations /home/gabe/projects/devops]
scanned 172876 directories, 622536 files in 1:48
panic: client.PutObject: Put https://s3-us-west-2.amazonaws.com/backup.slatebox/restic/data/88/880f109d1cb23cc04448623e8134054d1b4445c69be62786ef1b14d42cf125fc: dial tcp 54.231.176.224:443: connect: network is unreachable

goroutine 21394 [running]:
restic/archiver.(*Archiver).saveChunk(0xc4201d4f00, 0xc19460, 0xc420018408, 0xc65b3d, 0x594d7b, 0xd928754100000, 0xc424592000, 0x594d7b, 0x5e4000, 0xc4202d6630, ...)
	src/restic/archiver/archiver.go:165 +0x395
created by restic/archiver.(*Archiver).SaveFile
	src/restic/archiver/archiver.go:239 +0x3a4
```

With `s3.connections=2`

To be determined, but it's been uploading for 45 minutes and there's an estimated 45 minutes left. That's the longest and furthest I've gotten yet. I will report back if it succeeds/fails.

**Comment by fd0** [comment]
What's your upstream bandwidth? We've had a similar case in #1013, which is probably caused by too many connections on a very narrow upstream bandwidth...

**Comment by gabesullice** [comment]
Success with `s3.connections=2`!

It averages just about ~1.5 Mb/s.

**Comment by fd0** [comment]
Thanks! I'll merged the branch later today, I've added a comment about future plans here: https://github.com/restic/restic/issues/1013#issuecomment-307752029

**Comment by gabesullice** [comment]
Thanks for all your help! Great project!

**Comment by fd0** [comment]
The branch is merged, thanks for your patience!
