### ISSUE TITLE
Init fails on samba mount

### ISSUE THREAD

**Issue by rumpelsepp** [restic/restic#1120]
I have a samba mount using gvfs and init fails with

```
$ restic -r .
create key in backend at . failed: chmod keys/5819927c01c45558ec6df646b1cbe83f8be4d926d3103392775e14693d009c3f: operation not supported
```

**Comment by fd0** [comment]
You did not fill out the issue template so I don't have any idea which version of restic you're using, so I can only guess. This issue should be resolved in the master branch. I'm going to close this issue, please test the latest master branch and if that does not work, please fill out the issue template. Thanks!

**Comment by rumpelsepp** [comment]
Sry for being in a hurry. I just wanted to drop the issue here, since I did't want to forget about it. I will wait for the debian 0.7 package and repeat the test. When the issue remain, I will fill out the template with more information. :)

**Comment by rumpelsepp** [comment]
This should be the relevant issue:
Duplicate of https://github.com/restic/restic/issues/1079
