### ISSUE TITLE
Second backup to sftp backend is slow

### ISSUE THREAD

**Issue by xulongwu4** [restic/restic#1338]
## Output of `restic version`
restic 0.7.3
compiled with go1.9 on linux/amd64

## How did you run restic exactly?
restic --exclude-caches --one-file-system -r sftp:xxx@xxxxx.xxx:remote/ backup local/

## Expected behavior
Restic should work like it was backing up to local machine

## Actual behavior
When I backed up the directory for this first time, it worked as expected. However, if I create a second snapshot, restic would re-transmit all the files again to the remote server even though these files were not finally written into the disk of the remote server (i.e., the second snapshot does very little space on the disk due to the deduplication process).

Because restic re-scan and transmit every file each time I do a snapshot even for the unchanged files, the whole process takes tremendous time when the repository is large. This makes automated backup to remote server impractical.

## Steps to reproduce the behavior
One should be able to reproduce this behavior when pushing the backup repository to a remote server.

## Do you have any idea what may have caused this?
From what I read, this is caused by the fact that file inode can be unstable for connection via sftp, sshfs or other network based drive. 

## Do you have an idea how to solve the issue?
This can be overcome by adding such an option as "--ignore-inode" (this is what borg did). This could lead to inaccurate file change detection. But it can also speed things up when backing up big repository to remote server.

**Comment by fd0** [comment]
Hi, thanks for the report.

First, I'd like to concentrate on what you observed. I understood that this issue is about restic taking a long time for a second backup when using the sftp backend. When you use a local directory it is fast. Is that correct?

I have the following questions/requests for you in order to diagnose the problem:
 * Can you please paste the output of `restic backup` (at least up to when in starts saving files) for such a second backup to an sftp backend?
 * What was the network bandwidth and local CPU load that you observe during that second backup?
 * How/why did you conclude that restic is "sending the files" to the backend again?

I'm pretty sure that this has nothing to do with any inodes, so I've changed the title to contain what you observed.

**Comment by xulongwu4** [comment]
Yeah that is my observation. I also want to mention that I forgot to add two options when I used to back up to remote server. I just updated my report above.

To show more info about this issue, I used restic to backup a directory of about 3 GB to a remote server and the output of the first backup is attached: 

    scan [/home/xxx/Desktop]
    scanned 430 directories, 18160 files in 0:00
    [3:12] 100.00%  16.207 MiB/s  3.039 GiB / 3.039 GiB  18590 / 18590 items  0 errors  ETA 0:00 
    duration: 3:12, 16.15MiB/s
    snapshot 099a147f saved

After that I did a second backup immediately without changing any file in the directory. The output is the following:

    using parent snapshot 099a147f
    scan [/home/dien/Desktop]
    scanned 430 directories, 18160 files in 0:00
    [0:16] 100.00%  194.486 MiB/s  3.039 GiB / 3.039 GiB  18590 / 18590 items  0 errors  ETA 0:00 
    duration: 0:16, 192.66MiB/s
    snapshot 72a64a05 saved

The second output still takes about 16 seconds with some finite transfer speed even if there is no changed files. This becomes worse when I tried to backup a directory larger than 100 GB and has much more complicated structure than the one I showed earlier. It took more than an hour for the second backup even though no files were modified. From the finite transfer speed I saw from the restic output, I think restic tried to transfer the files for the second back up, while it ought to skip these unchanged files.

The network bandwidth should not be a problem in my case as you can see from the output attached. The CPU load is normal. most of the time it is between 10-30%

The server is a remote machine.

I thought it is due to unstable inodes because I saw the same issue when I tried borg at the beginning. Then I added the option "--ignore-inode" and it became normal. The second backup took effectively no time.

**Comment by fd0** [comment]
Thanks for reporting back!

What you see is restic loading metadata from the repo on demand during the backup, that's why it takes 16 seconds for just ~3GiB. We've addressed this is the master branch already by adding a local metadata cache (see #1040). Give the master branch a try if you like, or wait for the next release. Please be aware that for existing repos you need to run `restic prune` with the cache enabled at least once for it to become fully effective.

So I'm going to close this issue for now. Please feel free to add further comments. Thanks!

**Comment by xulongwu4** [comment]
Thanks for your reply. I will try to use the master branch and if I still have this issue I will report back.

**Comment by xulongwu4** [comment]
I used the new release to backup a directory of several hundred GB using the sftp backend. The second backup is much faster now. I think this issue can be closed. Thanks.

**Comment by fd0** [comment]
Thanks for the feedback, I appreciate it.
