### ISSUE TITLE
Prune error: hash does not match id

### ISSUE THREAD

**Issue by jamesjwarren** [restic/restic#1596]
## Output of `restic version`
```
restic 0.8.1
compiled with go1.9.2 on linux/amd64
```

## How did you run restic exactly?
```
export GOOGLE_APPLICATION_CREDENTIALS=
export GOOGLE_PROJECT_ID=xyz
export RESTIC_REPOSITORY=gs:xyz:/restic
> restic forget --keep-daily 14 --keep-weekly 4 --keep-monthly 3 --prune
```

```
...
3 snapshots have been removed, running prune
counting files in repo
building new index for repo
[2:32:08] 100.00%  267296 / 267296 packs
repository contains 267296 packs (8872906 blobs) with 1.202 TiB
processed 8872906 blobs: 391104 duplicate blobs, 72.908 GiB duplicate
load all snapshots
find data that is still in use for 93 snapshots
[9:33:37] 100.00%  93 / 93 snapshots
found 2599583 of 8872906 data blobs still in use, removing 6273323 blobs
will remove 0 invalid files
will delete 26302 packs and rewrite 31477 packs, this frees 204.107 GiB
hash does not match id: want da8129b85e6293465f70f91ca7add69a24edd0290cd5d81c8e5779bf14a8ac0e, got d0c254cddddb0152cbb6620ad30a12047181430cecb46f5d3109a7536acfb979
github.com/restic/restic/internal/repository.Repack
        src/github.com/restic/restic/internal/repository/repack.go:54
main.pruneRepository
        src/github.com/restic/restic/cmd/restic/cmd_prune.go:274
main.runForget
        src/github.com/restic/restic/cmd/restic/cmd_forget.go:237
main.glob..func8
        src/github.com/restic/restic/cmd/restic/cmd_forget.go:24
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:698
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:783
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
        src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:736
main.main
        src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
        /usr/local/go/src/runtime/proc.go:195
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2337
```

## What backend/server/service did you use to store the repository?
Google cloud storage

## Expected behavior

Prune to complete successfully or suggest a way to rectify the error.

## Actual behavior

Steps during prune operation take a long time. Error returned during the pack deletion stage, unclear how to resolve.

## Steps to reproduce the behavior

Prune a large repository. (first time)

## Do you have any idea what may have caused this?

No

## Do you have an idea how to solve the issue?

Perhaps it would be useful to be able to resume a prune operation, rather than needing to re-run the lengthy find data step again.

## Did restic help you or made you happy in any way?

Restic is otherwise fantastic a very well designed backup tool.

**Comment by fd0** [comment]
Thanks for the report!

restic detected that a file in the repo was modified, the SHA256 hash of the content does not match the file name. Was, at some point, the repository stored on a normal hard disk? We've seen a few cases where restic was able to uncover hardware defects, but for a cloud service uploaded via HTTPS it's rather unlikely to be a hardware fault.

This case (running `prune` with a modified file) is not supported very well, I'm classifying this a bug.

**Comment by jamesjwarren** [comment]
The repo has never been stored on a normal hard disk. It started life on S3 using the now s3legacy repo layout, then transferred to gcs, migrated layout and now using native GCS. I doubt that has much bearing as it all seemed to go ok.

**Comment by NovacomExperts** [comment]
I confirm the same errors on a Digital Ocean space (never on HD or moved) using :

restic 0.8.1
compiled with go1.9.2 on linux/amd64

I was running :

`restic forget --prune --keep-last 7 `


```
...
find data that is still in use for 40 snapshots
id 86827ae89af96c292a2bbca354afb91fc03225775e826038f4525677ad3d82b1 not found in any index
github.com/restic/restic/internal/repository.(*MasterIndex).LookupSize
        src/github.com/restic/restic/internal/repository/master_index.go:54
...

```
Then crash

**Comment by ifedorenko** [comment]
@NovacomExperts  "id ... not found in any index" is not the same as "hash does not match id", I think you ran into a different problem.

**Comment by NovacomExperts** [comment]
@ifedorenko  You're right. I was drawn by the go output result.

I will fill out a new issue if unable to work around it.

Thanks

**Comment by fd0** [comment]
@NovacomExperts You've likely run into the bug described in https://forum.restic.net/t/error-loading-tree-check-prune-and-forget-gives-error-b2-backend/406, it is fixed in https://github.com/restic/restic/pull/1589 but isn't contained in any released version yet.

You can do the following: run `restic rebuild-index` once, and from then on use a beta version of restic, e.g. https://beta.restic.net/restic-v0.8.1-125-gc8cb9a95/, which does not provoke the issue any more.

**Comment by NovacomExperts** [comment]
@fd0  Thanks Alexander. Did `restic rebuld-index` and now using v0.8.1-126.

Pruning worked great but still having issue on `restic check` though. It just sits there for hours. When I ctrl-C it, it removed the lock and the last line mentions no error found. I'll monitor the betas for new fixes on that.

**Comment by fbartels** [comment]
Hi,

isn't this fix included in the recent 0.8.2 release? I just updated to the newest version and now wanted to prune my archive (got seemingly the same traceback with 0.8.1 as reported in this issue). After getting the error message `tree xxx not found in repository` i also issues a `rebuild-index`, but still get the error message.

```
$ sudo backup minio prune
password is correct
counting files in repo
building new index for repo
[0:21] 100.00%  8769 / 8769 packs
repository contains 8769 packs (739630 blobs) with 38.938 GiB
processed 739630 blobs: 2 duplicate blobs, 1.938 KiB duplicate
load all snapshots
find data that is still in use for 56 snapshots
tree bb4ac29d3c4ba7bee745f248fb0f890d4fd9247a1d6e8d7f6a1a14d512d193a3 not found in repository
github.com/restic/restic/internal/repository.(*Repository).LoadTree
        /tmp/restic-build-354782844/src/github.com/restic/restic/internal/repository/repository.go:615
github.com/restic/restic/internal/restic.FindUsedBlobs
        /tmp/restic-build-354782844/src/github.com/restic/restic/internal/restic/find.go:11
main.pruneRepository
        src/github.com/restic/restic/cmd/restic/cmd_prune.go:191
main.runPrune
        src/github.com/restic/restic/cmd/restic/cmd_prune.go:85
main.glob..func16
        src/github.com/restic/restic/cmd/restic/cmd_prune.go:25
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
        /tmp/restic-build-354782844/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:698
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /tmp/restic-build-354782844/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:783
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
        /tmp/restic-build-354782844/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:736
main.main
        src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
        /usr/local/go/src/runtime/proc.go:198
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2361
```

```
restic 0.8.2
compiled with go1.10 on linux/amd64
```

**Comment by fd0** [comment]
@fbartels The error message is different, so the problem restic reports to you and what this issue is about are completely different things. Can you try running `restic rebuild-index`? If that doesn't work, please report a new issue and fill out the issue template. Thanks!

**Comment by fbartels** [comment]
> I can't find any report that you made previously.

Yes, I assumed that this and my problem are the same. Will create a new ticket then. Thanks

**Comment by askielboe** [comment]
I've been seeing this issue lately when running prune on a spinning drive raid setup with > 1 TB of backup data.

I only recently discovered that my weekly prune job was failing. Going back through the logs I see that it fails on the same hash check every time (not surprisingly I guess):

```
repository 328abcf7 opened successfully, password is correct
counting files in repo
building new index for repo
[1:10:45] 100.00%  258238 / 258238 packs
incomplete pack file (will be removed): bda4b05c034fe778a0444bacf297b52f69d939a3bd69bc9d755e1c0dcdc59a32
(... lots of these ...)
incomplete pack file (will be removed): 175d2fbf05b16a975ff1744a66af04671345c1924c91288704c237c524db0ed3
repository contains 258172 packs (6092146 blobs) with 1.148 TiB
processed 6092146 blobs: 2523042 duplicate blobs, 206.536 GiB duplicate
load all snapshots
find data that is still in use for 293 snapshots
[5:34] 100.00%  293 / 293 snapshots
found 3226099 of 6092146 data blobs still in use, removing 2866047 blobs
will remove 66 invalid files
will delete 6015 packs and rewrite 53725 packs, this frees 244.345 GiB
hash does not match id: want 28d5bcd6e514e766feb70052c9b212069b47e09fe2d295f5fd27bce8d6999bdc, got 7a34c5089b7ec56803e1c0ed0ff21e446e31c25251809e571ecf2db07f2ac6c8
github.com/restic/restic/internal/repository.Repack
	src/github.com/restic/restic/internal/repository/repack.go:35
main.pruneRepository
	src/github.com/restic/restic/cmd/restic/cmd_prune.go:278
main.runPrune
	src/github.com/restic/restic/cmd/restic/cmd_prune.go:85
main.glob..func18
	src/github.com/restic/restic/cmd/restic/cmd_prune.go:25
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:762
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:852
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:800
main.main
	src/github.com/restic/restic/cmd/restic/main.go:86
runtime.main
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361
```

**Comment by askielboe** [comment]
`restic check --read-data` confirms what prune is saying, that the pack 28d5bcd has a wrong hash, i.e.: 7a34c50.

Checking the hash manually confirms that the pack in question indeed has a different hash than expected:

```
>>> restic cat pack 28d5bcd6e514e766feb70052c9b212069b47e09fe2d295f5fd27bce8d6999bdc | sha256sum
Warning: hash of data does not match ID, want
  28d5bcd6e514e766feb70052c9b212069b47e09fe2d295f5fd27bce8d6999bdc
got:
  7a34c5089b7ec56803e1c0ed0ff21e446e31c25251809e571ecf2db07f2ac6c8
7a34c5089b7ec56803e1c0ed0ff21e446e31c25251809e571ecf2db07f2ac6c8  -
```

Is there a recommended way to proceed? Would be nice to be able to free the 200 GB + that prune is able to reclaim.

**Comment by benibr** [comment]
Got the same error when running `prune` on an remote Btrfs which doesn't find any flipped bits during its scrub.

```
repository 1f31f066 opened successfully, password is correct
counting files in repo
building new index for repo
[3:11] 100.00%  59712 / 59712 packs
incomplete pack file (will be removed): 7b8ca927c0e7ebd4807ca0f22ad50354bd573f3ae56e8a58257db1d25383dfc5
incomplete pack file (will be removed): 9cb31b15a5285d49e78bc0e27d6aaf5144fe9861c3206795ffd694e2d68d57b7
repository contains 59710 packs (692755 blobs) with 285.302 GiB
processed 692755 blobs: 61216 duplicate blobs, 10.091 GiB duplicate
load all snapshots
find data that is still in use for 7 snapshots
[0:19] 100.00%  7 / 7 snapshots
found 630272 of 692755 data blobs still in use, removing 62483 blobs
will remove 2 invalid files
will delete 76 packs and rewrite 3360 packs, this frees 10.632 GiB
hash does not match id: want f5df6ac0c86db6c4f0cc658dd0d4606577f62dd2399bebbf8d079488c8284800, got 2d598dab6c42b3107ce4a01c8624b2e4f178039985dfa2e47db2fe0225860005
github.com/restic/restic/internal/repository.Repack
	src/github.com/restic/restic/internal/repository/repack.go:35
main.pruneRepository
	src/github.com/restic/restic/cmd/restic/cmd_prune.go:278
main.runPrune
	src/github.com/restic/restic/cmd/restic/cmd_prune.go:85
main.glob..func18
	src/github.com/restic/restic/cmd/restic/cmd_prune.go:25
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:762
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:852
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:800
main.main
	src/github.com/restic/restic/cmd/restic/main.go:86
runtime.main
	/usr/lib/go/src/runtime/proc.go:198
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:2361
```

`restic check --read-data` doesn't find any errors
```
pack 3f5612b6: not referenced in any index
pack 9542d30a: not referenced in any index
pack a2a2f620: not referenced in any index
3395 additional files were found in the repo, which likely contain duplicate data.
You can run `restic prune` to correct this.
check snapshots, trees and blobs
read all data
[51:25] 100.00%  57471 / 57471 items
duration: 51:25
no errors were found
```

**Comment by nixzahlen** [comment]
hmmm... seems like there are some / many of similar problems reported. I did so as well... on Win10, see https://github.com/restic/restic/issues/1908
I couldn't fix it and had to delete all the restic backup data and start-all-over. Since than I haven't seen this error (so far :| )

By now I have the feeling there is / was (???) something seriously broken deep inside restic.... :(

**Comment by fd0** [comment]
It's very odd, I don't currently know what's going on. Especially since @askielboe has a case where the underlying file indeed has a SHA256 hash that's different from the file name.

@askielboe can you please run `sha256sum` on the NAS itself? There's a small chance that data has been modified in transit (e.g. by some bug in the sftp client/server)?

Which backends do you all use? I've seen local, sftp, gs, anything else? It looks like it's not specific to the backend...

Can (all of) you re-run the failing prune while specifying a new cache dir, with `restic prune --cache-dir /path/to/temp/cache/dir`, so we can confirm the data is newly fetched from the repo?

**Comment by fd0** [comment]
I'd like to point out that there's a positive side to this: restic told you that something odd is going on and you cannot (currently) rely on all data in that particular repo :)

**Comment by askielboe** [comment]
Thanks for your response! I was eager to prune the unused packs and recover space, so I'm afraid I deleted the pack from the repository. Prune and checks completed without error after that. I will make sure to run the tests you described if I ever see the issue again.

I'm connecting to the NAS over sftp.

I noticed your comment in #1999 on using SIGINT to interrupt a restic backup, and how it can result in incomplete pack files. This may very well be what happened in my case as I haven't pruned the repo since I set it up 6 months ago, and the chance that a backup was SIGINTed in that interval is quite high.

It's definitely a good sign that restic discovers things like this! :)

Let me know if there is anything else I can do to help.

**Comment by fd0** [comment]
Hm, it's a bummer, but I can understand very well.

Is there anybody else who could run some tests for me to dig down into this issue?

**Comment by askielboe** [comment]
Seems like I did an `scp` (to be exact I think I used `sftp` and `get`) of the broken pack before removing it from the repo.

The `sha256sum` of that is the same as that from `restic cat`:

```
❯❯❯ gsha256sum 28d5bcd6e514e766feb70052c9b212069b47e09fe2d295f5fd27bce8d6999bdc
7a34c5089b7ec56803e1c0ed0ff21e446e31c25251809e571ecf2db07f2ac6c8  28d5bcd6e514e766feb70052c9b212069b47e09fe2d295f5fd27bce8d6999bdc
```
I also did an `ls -l` on the NAS before removing the pack and pruning:

```
❯❯❯ cd data/28
❯❯❯ ls -l 28d5bcd6e514e766feb70052c9b212069b47e09fe2d295f5fd27bce8d6999bdc
-rw------- 1 askielboe users  4708120 Mar 24 05:12 28d5bcd6e514e766feb70052c9b212069b47e09fe2d295f5fd27bce8d6999bdc
```

Then I checked the packs starting with `28` that were created around the same time. All had correct hashes. It could be a coincidence, but the broken pack seems to be the last that was written to the `28` folder during that backup session (the broken back is on the second to last line):

```
❯❯❯ cd data/28
❯❯❯ ls -lrt
(... truncated ...)
-rw------- 1 askielboe users  4865370 Mar 24 05:01 28cfb2dfd83272a253c83d8e84390c2d22a6190f90ee78e7fd5b049dfc2e50c2
-rw------- 1 askielboe users  6321192 Mar 24 05:04 28693acc3754f77cdde51e5267b8ba9430846064e6cd263f35665c6863567dab
-rw------- 1 askielboe users  4414743 Mar 24 05:05 285eff6026d59025a3cc1c08a165c39bf4301eb34c7a8b9307590129a938f8b0
-rw------- 1 askielboe users  5472757 Mar 24 05:08 282cfc3d8d81860593b07b4e93cedd0a996ae5585f6cd1426e1824276072e9c0
-rw------- 1 askielboe users  4392324 Mar 24 05:09 28d9c3142c155041f109d14421663cc953d37147b81d15ef84e75ea1892e1511
-rw------- 1 askielboe users  5456418 Mar 24 05:09 28da1a39f148742376663d5f4c940888008af5416b609f9133d7609a853a5a97
-rw------- 1 askielboe users  4900605 Mar 24 05:10 2800ad38b6d7ca98a0dbde542dce29316c77833f2aab9003dc4ed73917b6b752
-rw------- 1 askielboe users  5162871 Mar 24 05:11 28f8ee89e6abd44d79c944603f7207830054a2aec70d322916411de0bda7dc2b
-rw------- 1 askielboe users  4708120 Mar 24 05:12 28d5bcd6e514e766feb70052c9b212069b47e09fe2d295f5fd27bce8d6999bdc <--- Broken pack
-rw------- 1 askielboe users  5290941 Mar 24 14:03 28d3616b150c0a5c9ea73440fb14f34857874348caa047b1aa79e79a2ee891d6
(... truncated ...)
```

After deleting pack `28d5bcd6e514e766feb70052c9b212069b47e09fe2d295f5fd27bce8d6999bdc` and pruning it looks like this:

```
❯❯❯ cd data/28
❯❯❯ ls -lrt --time-style=full-iso
(... truncated ...)
-rw-------   1 askielboe users  4865370 2018-03-24 05:01:58.683692086 +0100 28cfb2dfd83272a253c83d8e84390c2d22a6190f90ee78e7fd5b049dfc2e50c2
-rw-------   1 askielboe users  6321192 2018-03-24 05:04:52.972685941 +0100 28693acc3754f77cdde51e5267b8ba9430846064e6cd263f35665c6863567dab
-rw-------   1 askielboe users  4414743 2018-03-24 05:05:08.540685196 +0100 285eff6026d59025a3cc1c08a165c39bf4301eb34c7a8b9307590129a938f8b0
-rw-------   1 askielboe users  5472757 2018-03-24 05:08:38.851686312 +0100 282cfc3d8d81860593b07b4e93cedd0a996ae5585f6cd1426e1824276072e9c0
-rw-------   1 askielboe users  4392324 2018-03-24 05:09:33.891690788 +0100 28d9c3142c155041f109d14421663cc953d37147b81d15ef84e75ea1892e1511
-rw-------   1 askielboe users  5456418 2018-03-24 05:09:46.596687054 +0100 28da1a39f148742376663d5f4c940888008af5416b609f9133d7609a853a5a97
-rw-------   1 askielboe users  4900605 2018-03-24 05:10:32.348686466 +0100 2800ad38b6d7ca98a0dbde542dce29316c77833f2aab9003dc4ed73917b6b752
-rw-------   1 askielboe users  5290941 2018-03-24 14:03:34.743689137 +0100 28d3616b150c0a5c9ea73440fb14f34857874348caa047b1aa79e79a2ee891d6
(... truncated ...)
```

The pack seems to have been created along with some of the earliest snapshots:

```
ID        Date                 Host                        Tags        Directory
----------------------------------------------------------------------
2443fdf9  2018-03-23 18:55:30  work-MacBook-Pro.local              /Users/askielboe
29e71cfe  2018-03-24 00:18:30  home-MacBook-Pro.local              /Users/askielboe
783728d9  2018-03-24 09:24:13  work-MacBook-Pro.local              /Users/askielboe
fbfa0cf6  2018-03-24 10:36:03  home-MacBook-Pro.local              /Volumes/BACKUP/Lightroom CC
58b3a756  2018-03-26 20:00:20  work-MacBook-Pro.local              /Users/askielboe
```

Because I prune per-host and have since manually specified my hostname I don't think those snapshots have been pruned. I usually prune down to one snapshot per week. So I believe those first snapshots should be intact. If this is the case it could indicate an interrupted backup, but I cant't say with 100 % certainty that this is indeed the case.

I checked all the index files using `restic cat index` and `map(select(.id | contains ID)` as you suggested in the other issue, and pack is not present in any of them anymore.

Anything else I can check with the stuff that I have?

**Comment by fd0** [comment]
> Anything else I can check with the stuff that I have?

That was very comprehensive, thanks!

> If this is the case it could indicate that the broken pack was written as part of an interrupted backup, since none of the existing snapshots reference the pack (if I understand the cat index output correctly?).

Ah no, I don't think that's plausible. I need to go into the details so you can understand my reasoning:

The files restic stores in the repo follow the [pack format](https://restic.readthedocs.io/en/latest/100_references.html#pack-format) described in the design document. A file consists of a list of encrypted blobs (e.g. parts of files, or metadata) followed by an encrypted header, followed by the header length. If a file could not be written completely, either the header length at the very end of the file or the header itself cannot be read (and decrypted) successfully. By trying to read and decrypt the header at the end of the file, restic detects invalid files left over by an aborted run of `restic backup`. Invalid files are just removed from the repo at the end of the `purne` run.

Restic also makes a list of all blobs and files in the repo in so-called index files. A file is only saved in an index file after a successful upload. So files uploaded during interrupted backup runs don't get inserted into index files and are removed on the next run of `prune`.

Next, I'll write some code that @carlonluca can run on their repo, and if you copy the file back to your repo you can also test it.

**Comment by askielboe** [comment]
Ah right, thanks for the explanation. That definitely makes sense. I'll be happy to copy the file back so we can try your code.

**Comment by deanroker123** [comment]
I have a repository running on Wasabi, I was running prune and got this message

`hash does not match id: want a019d2d52f4f5f8f7c07c8ae157134c1538c5d503acdc4e5565315541f7e3c41, got d38989cef0381e60eba0f155caba53f4a8f9badfaf89fc92b15f29592899f4db
github.com/restic/restic/internal/repository.Repack
	/restic/internal/repository/repack.go:35
main.pruneRepository
	/restic/cmd/restic/cmd_prune.go:278
main.runPrune
	/restic/cmd/restic/cmd_prune.go:85
main.glob..func18
	/restic/cmd/restic/cmd_prune.go:25
github.com/spf13/cobra.(*Command).execute
	/restic/vendor/github.com/spf13/cobra/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
	/restic/vendor/github.com/spf13/cobra/command.go:852
github.com/spf13/cobra.(*Command).Execute
	/restic/vendor/github.com/spf13/cobra/command.go:800
main.main
	/restic/cmd/restic/main.go:86
runtime.main
	/usr/local/go/src/runtime/proc.go:201
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1333` 

 When I check the sha256 sum of that file it is correct. I have cleared the cache and started the process again. I have been getting lots of these types of errors over the last few days. 
`Save(<data/a428ef089b>) returned error, retrying after 360.814902ms: client.PutObject: 503 Service Unavailable
Save(<data/ddf5bdca97>) returned error, retrying after 301.874165ms: client.PutObject: 503 Service Unavailable
Save(<data/a28fd84703>) returned error, retrying after 348.774344ms: client.PutObject: 503 Service Unavailable
Save(<data/dee4344e5e>) returned error, retrying after 563.500552ms: client.PutObject: 503 Service Unavailable`
Could the file have been half downloaded and not cached correctly?

**Comment by deanroker123** [comment]
I mounted the repo with rclone and did it on the repo data. I had it happen again on another hash, I will check the cache now.

**Comment by deanroker123** [comment]
Ok so the new file (cdc75465bde4cca54505d2ed3979394ea41ae43d4226aee3cda72989bb640d44) isn't in the cache but on the server (mounted with rclone again) it checks out. Any ideas? could it be memory issues? Or still related to the errors, as well as the 503 errors I got these as well just before the hash problem.
`
Load(<data/2605ba40aa>, 0, 0) returned error, retrying after 291.004563ms: We encountered an internal error.  Please retry the operation again later.
Load(<data/2605ba40aa>, 0, 0) returned error, retrying after 402.595127ms: We encountered an internal error.  Please retry the operation again later.
`

**Comment by deanroker123** [comment]
prune finished running without any more errors. I guess the problem was network related rather than data related. Would it be worth having another error message for this scenario? I am not sure how you could recreate the problem though to be able to test it for sure.

**Comment by MichaelEischer** [comment]
Closing this as the issue is already quite old and I don't think there's any left to investigate here. Better handling data corruption while downloading files should be discussed in #2302.

If the reported problems persist with a recent restic version, please open a new issue.
