### ISSUE TITLE
Panic on unexpected status code when using REST repository

### ISSUE THREAD

**Issue by sorcix** [restic/restic#1771]
## Output of `restic version`

```
$ restic version
restic 0.8.3
compiled with go1.10 on darwin/amd64
```

## How did you run restic exactly?

```
$ restic -r rest:https://username:password@server/ backup --one-file-system --exclude-file /Users/username/.backup-ignore /Users/username
enter password for repository:
password is correct
scan [/Users/username]
scanned 33198 directories, 210581 files in 0:19
Save(<data/f9b4d477d4>) returned error, retrying after 319.4786ms: server response unexpected: 413 Request Entity Too Large (413)
Save(<data/7a73793923>) returned error, retrying after 721.128989ms: server response unexpected: 413 Request Entity Too Large (413)
Save(<data/6e39be9fb1>) returned error, retrying after 419.147889ms: server response unexpected: 413 Request Entity Too Large (413)
Save(<data/48780241b3>) returned error, retrying after 293.937626ms: server response unexpected: 413 Request Entity Too Large (413)
Save(<data/15f68bf752>) returned error, retrying after 318.891111ms: server response unexpected: 413 Request Entity Too Large (413)
Save(<data/d8db44b222>) returned error, retrying after 564.972949ms: server response unexpected: 413 Request Entity Too Large (413)
Save(<data/76254fe0a6>) returned error, retrying after 414.306207ms: server response unexpected: 413 Request Entity Too Large (413)
Save(<data/0ea43cb463>) returned error, retrying after 294.616072ms: server response unexpected: 413 Request Entity Too Large (413)
Save(<data/7688a3b399>) returned error, retrying after 725.645531ms: server response unexpected: 413 Request Entity Too Large (413)
Save(<data/afb608ab77>) returned error, retrying after 400.926667ms: server response unexpected: 413 Request Entity Too Large (413)
Save(<data/22bf47ae2c>) returned error, retrying after 345.170198ms: server response unexpected: 413 Request Entity Too Large (413)
Save(<data/ad929423bc>) returned error, retrying after 571.77044ms: server response unexpected: 413 Request Entity Too Large (413)
Save(<data/6589dc6486>) returned error, retrying after 371.242809ms: server response unexpected: 413 Request Entity Too Large (413)
Save(<data/efa57fd0e2>) returned error, retrying after 623.381248ms: server response unexpected: 413 Request Entity Too Large (413)
Save(<data/7597775aec>) returned error, retrying after 662.216668ms: server response unexpected: 413 Request Entity Too Large (413)
Save(<data/42780de57e>) returned error, retrying after 365.524175ms: server response unexpected: 413 Request Entity Too Large (413)
[17:18] 1.28%  444.596 MiB / 33.832 GiB  7771 / 243779 items  0 errors  ETA 22:10:46
error while saving data to the repo: server response unexpected: 413 Request Entity Too Large (413)
github.com/restic/restic/internal/backend/rest.(*restBackend).Save
        /tmp/restic-build-881482904/src/github.com/restic/restic/internal/backend/rest/rest.go:146
github.com/restic/restic/internal/backend.(*RetryBackend).Save.func1
        /tmp/restic-build-881482904/src/github.com/restic/restic/internal/backend/backend_retry.go:71
github.com/restic/restic/vendor/github.com/cenkalti/backoff.RetryNotify
        /tmp/restic-build-881482904/src/github.com/restic/restic/vendor/github.com/cenkalti/backoff/retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).retry
        /tmp/restic-build-881482904/src/github.com/restic/restic/internal/backend/backend_retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).Save
        /tmp/restic-build-881482904/src/github.com/restic/restic/internal/backend/backend_retry.go:65
github.com/restic/restic/internal/cache.(*Backend).Save
        /tmp/restic-build-881482904/src/github.com/restic/restic/internal/cache/backend.go:55
github.com/restic/restic/internal/repository.(*Repository).savePacker
        /tmp/restic-build-881482904/src/github.com/restic/restic/internal/repository/packer_manager.go:107
github.com/restic/restic/internal/repository.(*Repository).SaveAndEncrypt
        /tmp/restic-build-881482904/src/github.com/restic/restic/internal/repository/repository.go:257
github.com/restic/restic/internal/repository.(*Repository).SaveBlob
        /tmp/restic-build-881482904/src/github.com/restic/restic/internal/repository/repository.go:611
github.com/restic/restic/internal/archiver.(*Archiver).Save
        /tmp/restic-build-881482904/src/github.com/restic/restic/internal/archiver/archiver.go:105
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk
        /tmp/restic-build-881482904/src/github.com/restic/restic/internal/archiver/archiver.go:170
runtime.goexit
        /usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361
panic: server response unexpected: 413 Request Entity Too Large (413)

goroutine 3572 [running]:
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk(0xc4206331a0, 0x1758380, 0xc420246680, 0x800000, 0x5dd372, 0xe41f045600000, 0xc425482000, 0x5dd372, 0x5e4000, 0xc420425a20, ...)
        /tmp/restic-build-881482904/src/github.com/restic/restic/internal/archiver/archiver.go:175 +0x3d8
created by github.com/restic/restic/internal/archiver.(*Archiver).SaveFile
        /tmp/restic-build-881482904/src/github.com/restic/restic/internal/archiver/archiver.go:249 +0x39e
```

## What backend/server/service did you use to store the repository?

The rest-server behind an nginx proxy that had maximum body size limited (which caused the Request Entity Too Large status.)

## Expected behavior

Error count updates correctly and restic does not panic but shows an error message.

## Actual behavior

Error count stays at 0 and restic suddenly panics.

## Steps to reproduce the behavior

Limit the body size on the rest-server and try to backup large files.

## Do you have any idea what may have caused this?

Wrong configuration on nginx reverse proxy sitting in front of the rest-server triggers errors that aren't handled.

## Do you have an idea how to solve the issue?

Improve error handling.

## Did restic help you or made you happy in any way?

Restic is the best backup product I've used so far. Simple to use and so fast! (I love that you can retry failed backups and it'll skip everything that was uploaded in the last try.)

**Comment by fd0** [comment]
Thanks for the report! Handling backend errors was not good within restic, but we've recently fixed it and the last step for that was the PR #1770 I've just merged. Would you mind retrying with the version from the master branch? You can find compiled binaries of the restic master branch with the proper error handling here (in about two minutes): https://beta.restic.net/restic-v0.8.3-242-g580f90d7/

**Comment by sorcix** [comment]
Must be the fastest bugfix ever. ;-)

```
$ restic version
restic 0.8.3 (v0.8.3-242-g580f90d7) compiled with go1.10.2 on darwin/amd64
```

Looks like it doesn't panic anymore, but I don't know what it does with the errors now. Seems to continue. It has been about 10 minutes since it last said "retry in 11 seconds". As you can see the ETA is quite long (slow repository) so I'll let you know what happens if it does decide to stop. :-)

```
Save(<data/01ec91059c>) returned error, retrying after 304.843644ms: server response unexpected: 413 Request Entity Too Large (413)ments/Projects/2017-02-05-quizmachine/LPCXpresso/LPCXpresso_7.6.2_326.exe
Save(<data/01ec91059c>) returned error, retrying after 719.110824ms: server response unexpected: 413 Request Entity Too Large (413)ments/Projects/2017-02-05-quizmachine/LPCXpresso/LPCXpresso_7.6.2_326.exe
Save(<data/01ec91059c>) returned error, retrying after 1.568626547s: server response unexpected: 413 Request Entity Too Large (413)ments/Projects/2017-02-05-quizmachine/LPCXpresso/LPCXpresso_7.6.2_326.exe
Save(<data/01ec91059c>) returned error, retrying after 2.327888975s: server response unexpected: 413 Request Entity Too Large (413)ments/Projects/2017-02-05-quizmachine/LPCXpresso/LPCXpresso_7.6.2_326.exe
Save(<data/01ec91059c>) returned error, retrying after 1.476223173s: server response unexpected: 413 Request Entity Too Large (413)ments/Projects/2017-02-05-quizmachine/LPCXpresso/LPCXpresso_7.6.2_326.exe
Save(<data/01ec91059c>) returned error, retrying after 5.404596418s: server response unexpected: 413 Request Entity Too Large (413)ments/Projects/2017-02-05-quizmachine/LPCXpresso/LPCXpresso_7.6.2_326.exe
Save(<data/01ec91059c>) returned error, retrying after 6.452766868s: server response unexpected: 413 Request Entity Too Large (413)ments/Projects/2017-02-05-quizmachine/LPCXpresso/LPCXpresso_7.6.2_326.exe
Save(<data/01ec91059c>) returned error, retrying after 10.52994176s: server response unexpected: 413 Request Entity Too Large (413)ments/Projects/2017-02-05-quizmachine/LPCXpresso/LPCXpresso_7.6.2_326.exe
Save(<data/01ec91059c>) returned error, retrying after 11.618792568s: server response unexpected: 413 Request Entity Too Large (413)ents/Projects/2017-02-05-quizmachine/LPCXpresso/LPCXpresso_7.6.2_326.exe
Save(<data/01ec91059c>) returned error, retrying after 11.302711181s: server response unexpected: 413 Request Entity Too Large (413)ents/Projects/2017-02-05-quizmachine/LPCXpresso/LPCXpresso_7.6.2_326.exe
[14:47] 2.23%  5919 files 774.311 MiB, total 203624 files 33.834 GiB, 0 errors ETA 10:46:41
/Users/username/Documents/Projects/2017-02-05-quizmachine/MAC  - LPCXpresso.rar
/Users/username/Documents/Projects/2017-02-05-quizmachine/MAC  - LPCXpresso.rar
```

It also seems to show which files it's working on (awesome!) but that seems to mess up the error messages a bit in my terminal: the last part of the path is appended after the error message.

**Comment by sorcix** [comment]
Looks like restic just hangs now, status is still the same 30 minutes later:

```
[43:56] 2.23%  5919 files 774.311 MiB, total 203624 files 33.834 GiB, 0 errors ETA 32:01:50
```

**Comment by fd0** [comment]
Found an error, PR incoming
