### ISSUE TITLE
Error in restoring a specific file

### ISSUE THREAD

**Issue by vitor10prado** [restic/restic#1870]
When I run the command to restore a specific file, the restic return the follow error:
```
ignoring error for /restore11/usr/local/teste2.txt: OpenFile: open /restore11/usr/local/teste2.txt: is a directory
```

## Output of `restic version`
(v0.9.1-33-g44fb2a8) compiled with go1.10.3 on linux/amd64

## How did you run restic exactly?

 restic restore d84bbf60 -t /restore11/ -i "/usr/local/teste2.txt"

## What backend/server/service did you use to store the repository?

S3 ( DigitalOcean )

## Expected behavior

 Restic should not convert the file to directory

## Actual behavior

 
Restoring specific file from a snapshot , restic convert the first file to directory 

## Steps to reproduce the behavior

```
root@gbox:/# restic restore d84bbf60 -t /restore11/ -i "/usr/local/*.txt"
repository 00d74122 opened successfully, password is correct
restoring <Snapshot d84bbf60 of [/usr/local] at 2018-07-01 19:45:00.798260419 +0000 UTC by root@gbox> to /restore11/
ignoring error for /restore11/usr/local/teste2.txt: OpenFile: open /restore11/usr/local/teste2.txt: is a directory
There were 1 errors
```

Linting the file/directory

```
root@gbox:/# ls -l /restore11/usr/local/
total 12
drwx------ 2 root root 4096 Jul  1 21:41 teste2.txt
```

## Do you have any idea what may have caused this?

no

## Do you have an idea how to solve the issue?

no

**Comment by fd0** [comment]
Hm, that's odd. Thanks for the report!

Would you mind running the following command so that we can see what's in the restic repo?

```
$ restic ls -l d84bbf60 | grep usr/local/teste2
```

**Comment by vitor10prado** [comment]
Folow the result:

root@gbox:~# restic ls -l d84bbf60 | grep usr/local/teste2
-rw-r--r--     0     0      7 2018-07-01 16:48:11 /usr/local/teste2.txt

**Comment by fd0** [comment]
I've only just discovered the cause for this issue yesterday by accident, it's resolved in #1885 and already merged into the master branch. 
You can find compiled binaries of the restic master branch here: https://beta.restic.net/?sort=time&order=desc

The issue occurred when you have a file at the top level in a snapshot and tried to restore this file to a directory which did not exist yet.

I'm closing this issue. Please leave feedback if it works for you with the beta binaries (or self-compiled from master). Thanks!

**Comment by cd1188** [comment]
errror is not fixed..
restic 0.9.1 (v0.9.1-50-g67535e0-dirty) compiled with go1.10.2 on windows/amd64

this is a 26mb file and not a directory... it restored only a empty directory 'Andrea'
ignoring error for c:\restore\d\daten_mozilla\Thunderbird\Local\Andrea: OpenFile: open \\?\c:\restore\d\daten_mozilla\Thunderbird\Local\Andrea: is a directory
There were 1 errors

**Comment by fd0** [comment]
Hm, odd.

**Comment by fd0** [comment]
@cd1188 can you please paste the command line for restic, the complete output and the output of `restic ls -l` for the snapshot you tried to restore? Thanks!

**Comment by cd1188** [comment]
--> v0.9.1-27 works fine
--> since v0.9.1-31 there is the error
--> the error is only if i use the --include option


#### RESTORING ####

C:\restic>restic_v0.9.1-27-g8dae2de2_windows_amd64 -r c:\repo restore latest --target c:\restore --include "\c\daten_mozilla\Thunderbird\Local"
enter password for repository:
repository 69e36d19 opened successfully, password is correct
restoring <Snapshot 9484e411 of [c:\daten_mozilla] at 2018-07-20 19:42:56.3411041 +0200 CEST by XXXXXX> to c:\restore

C:\restic>

C:\restic>restic_v0.9.1-31-g7ddf91b6_windows_amd64 -r c:\repo restore latest --target c:\restore --include "\c\daten_mozilla\Thunderbird\Local"
enter password for repository:
repository 69e36d19 opened successfully, password is correct
restoring <Snapshot 9484e411 of [c:\daten_mozilla] at 2018-07-20 19:42:56.3411041 +0200 CEST by XXXXXX> to c:\restore
ignoring error for c:\restore\c\daten_mozilla\Thunderbird\Local\Andrea: OpenFile: open \\?\c:\restore\c\daten_mozilla\Thunderbird\Local\Andrea: is a directory
There were 1 errors

C:\restic>

C:\restic>restic_v0.9.1-31-g7ddf91b6_windows_amd64 -r c:\repo restore latest --target c:\restore --include "\c\daten_mozilla\Thunderbird\Local\Andrea"
enter password for repository:
repository e8d2a6cb opened successfully, password is correct
restoring <Snapshot 730f95d4 of [c:\daten_mozilla] at 2018-07-20 20:09:02.9578246 +0200 CEST by XXXXXX> to c:\restore
ignoring error for c:\restore\c\daten_mozilla\Thunderbird\Local\Andrea: OpenFile: open \\?\c:\restore\c\daten_mozilla\Thunderbird\Local\Andrea: is a directory
There were 1 errors

C:\restic>

C:\restic>restic_v0.9.1-31-g7ddf91b6_windows_amd64 -r c:\repo restore latest --target c:\restore
enter password for repository:
repository 69e36d19 opened successfully, password is correct
restoring <Snapshot 9484e411 of [c:\daten_mozilla] at 2018-07-20 19:42:56.3411041 +0200 CEST by XXXXXX> to c:\restore

C:\restic>

#### LIST ####
C:\restic>restic -r c:\repo ls -l 730f95d4
enter password for repository:
repository e8d2a6cb opened successfully, password is correct
snapshot 730f95d4 of [c:\daten_mozilla] at 2018-07-20 20:09:02.9578246 +0200 CEST):
drwxrwxrwx     0     0      0 2018-07-20 19:37:40 /c
drwxrwxrwx     0     0      0 2018-07-20 19:40:43 /c/daten_mozilla
drwxrwxrwx     0     0      0 2018-07-20 19:41:01 /c/daten_mozilla/Thunderbird
drwxrwxrwx     0     0      0 2018-07-20 20:08:47 /c/daten_mozilla/Thunderbird/Local
-rw-rw-rw-     0     0 26959709 2012-02-29 11:41:28 /c/daten_mozilla/Thunderbird/Local/Andrea
-rw-rw-rw-     0     0  91815 2018-06-25 18:40:39 /c/daten_mozilla/Thunderbird/Local/Andrea.msf
-rw-rw-rw-     0     0 235694 2016-08-18 19:31:50 /c/daten_mozilla/Thunderbird/Local/Archiv
-rw-rw-rw-     0     0  21958 2018-07-01 14:32:57 /c/daten_mozilla/Thunderbird/Local/Archiv.msf
-rw-rw-rw-     0     0      0 2003-08-15 14:05:58 /c/daten_mozilla/Thunderbird/Local/Outlook
-rw-rw-rw-     0     0   2476 2018-02-16 08:58:57 /c/daten_mozilla/Thunderbird/Local/Outlook.msf
drwxrwxrwx     0     0      0 2008-07-23 14:29:49 /c/daten_mozilla/Thunderbird/Local/Templates.sbd
drwxrwxrwx     0     0      0 2008-07-23 14:29:49 /c/daten_mozilla/Thunderbird/Local/Unsent Messages.sbd
-rw-rw-rw-     0     0 137546380 2018-06-13 23:26:08 /c/daten_mozilla/Thunderbird/Local/Wohnung
-rw-rw-rw-     0     0 263260 2018-06-25 18:48:36 /c/daten_mozilla/Thunderbird/Local/Wohnung.msf
-rw-rw-rw-     0     0  58800 2017-07-31 13:13:08 /c/daten_mozilla/Thunderbird/Local/adobe
-rw-rw-rw-     0     0   4938 2018-06-25 18:39:57 /c/daten_mozilla/Thunderbird/Local/adobe.msf

C:\restic>

#### NEW REPO ####
if i make a new repository and remove in the source-folder the file Andrea the error is now on the Archiv-File

C:\restic>restic -r c:\repo2 restore latest --target c:\restore --include "\c\daten_mozilla\Thunderbird\Local"
enter password for repository:
repository 1334a375 opened successfully, password is correct
restoring <Snapshot cc3eb977 of [c:\daten_mozilla] at 2018-07-20 20:19:36.9734525 +0200 CEST by XXXXXX> to c:\restore
ignoring error for c:\restore\c\daten_mozilla\Thunderbird\Local\Archiv: OpenFile: open \\?\c:\restore\c\daten_mozilla\Thunderbird\Local\Archiv: is a directory
There were 1 errors

C:\restic>

**Comment by fd0** [comment]
Thank you very much, I can reproduce it!

**Comment by fd0** [comment]
A `git bisect` says 5fa6dc53cb4faacf6314b40693a1813fa4d9c26c is the commit which introduced the behavior.

**Comment by fd0** [comment]
@ifedorenko please don't worry about this, it's perfectly normal and human! I think we're handling it pretty well, especially by adding more test cases :) I agree that the restorer had not enough test cases from the start.

I'm currently working on this, I'll let you know here in the issue if I hit a wall or so.

Thank you all for your contributions (bug reports and code)!

**Comment by fd0** [comment]
PR #1900 contains the test case.

**Comment by fd0** [comment]
Mh. This is complicated. I'll add an explanation to the PR, in case you want to follow @ifedorenko.
