### ISSUE TITLE
"Data blobs seem to be missing" error during prune on Backblaze

### ISSUE THREAD

**Issue by adworacz** [restic/restic#3266]
Output of `restic version`
--------------------------
`restic 0.11.0 compiled with go1.15.3 on linux/amd64`

How did you run restic exactly?
-------------------------------
```
export B2_ACCOUNT_ID=...
export B2_ACCOUNT_KEY=...
export RESTIC_REPOSITORY=...
export RESTIC_PASSWORD_FILE=...
restic prune -vvv /path/to/dir
```

Output:

```
repository 06abe926 opened successfully, password is correct
counting files in repo
building new index for repo
[27:32:39] 100.00%  597407 / 597407 packs
incomplete pack file (will be removed): 003dec62564216e7819241c370154097d705b39c17e146ac5a6ba46f20913727
incomplete pack file (will be removed): 007e2a5d9070758730ed30e92763baf1633b58c32297a2d35f48798c6e24cfcb
incomplete pack file (will be removed): 03f8c59984daa1df72fa03b893ace7b9482eca8749166b39505d2ccd20672f7a
incomplete pack file (will be removed): 0582dcc70d68388def5c8898fed9066195f2975933eeae1ba7e8d93220385322
incomplete pack file (will be removed): 087dd11ad6890e87cf58cb075e0c2921a5204b04005d0c62f4b7c77579b42b2d
incomplete pack file (will be removed): 090f679d2d613f88bed226b7b689e1f7be675081f0a622ec962d312a949bd82d
incomplete pack file (will be removed): 095e265e665613d4c75317036861be77c43118dab78d0ea861788a1ecbb9e5ae
incomplete pack file (will be removed): 0a8fbcd5a0b7fcc2f31ecc3a2cad94857935b68bcea00be36b23d0f6230f2fa8
incomplete pack file (will be removed): 0b5e68125dfe12fa9035f78f70e98f0e2841853301486e4fd6a76ea56bb0f27a
incomplete pack file (will be removed): 0bd0515bc4a5fce93fb43f5999a7c57326198f201a088cb6cb4e899022b607a5
incomplete pack file (will be removed): 0cb0d8387b592be4a8c9af6dfbc50eab88631c56a892d3e9f53bd2d3ba8a2c7d
incomplete pack file (will be removed): 0ec5f045bc6e906da140a2bdaacfbdda09bcee8bf80ef8a47f7006db3fa4540b
incomplete pack file (will be removed): 10d03a20dec814751a2ca0bb211155842426788f93c09b00adf4ef686cc69ee7
incomplete pack file (will be removed): 14671c360e4e0070ac534257f04ec2d9f54eaa726dc02e33c49c794335666b0e
incomplete pack file (will be removed): 17559ab4f99881b2cb2b2e5e38776f15e2afdfac1c20cb873aa34d15b276fecd
incomplete pack file (will be removed): 17ae81809bc5fb38b2d3d797d176a929c10eaedf4d9569b128f767127c8836f8
incomplete pack file (will be removed): 1ad794f10507933f0fb922b26d2ac613a95aa3ed1e0aa2c32a99772fe9be436f
incomplete pack file (will be removed): 1c38cc7ddf296594b35841c902fe29b658bb5599e10fffa0343ef5747660a38b
incomplete pack file (will be removed): 1cae5e441b86dc564c6e5f4288e5d6550c989a7cd1fd7b7d05ee98dc62567d7e
incomplete pack file (will be removed): 1cd22f6b1ed9825eaf19ef14fd58f2741d0028bf94bd3939a3e3ed7e611f8c38
incomplete pack file (will be removed): 213184f2970f6af57db6d85bc84c2e8a7c33d713b0c3d4a496bea8138fe3bbe2
incomplete pack file (will be removed): 2245429bcc727256c243aa92d8de2d1415a2d412873e46f624793f39bfab2c14
incomplete pack file (will be removed): 255f6dbbcc5e9b60adbb42f06c144b10b304dc43e31eefc29cd3f974c100239e
incomplete pack file (will be removed): 2a34d963f6c706696335e1d4bda6741e01deeca162b8e983c7ecf2b542d73c94
incomplete pack file (will be removed): 2ac52911df5c641930ae8426c9728b32c0eb3c01a1cc34d66baf2722682a076b
incomplete pack file (will be removed): 2b80ed34c0db40cb2a6ec9634748e82a206f1b0620286dca9b2c08086033dff2
incomplete pack file (will be removed): 2d1368e95d4070be66524a10e9e58b9a9486a345cf22b9274ebeb934854b6d67
incomplete pack file (will be removed): 4e3d88deffff0698abf384172b9f54a6155b244d8d537e161558b1327b867ff2
incomplete pack file (will be removed): 4efd7ecf622374cef4a21b2162ef0838e6c3a14ccc773e17cf0291b1966ac745
incomplete pack file (will be removed): 957b9ef669e0652276221cba51f61794020e43fc6792b4066c03e4767510d152
incomplete pack file (will be removed): cf83988c27cd94128395478acde1b3575e0803a9897505a291b742c38bd43d71
incomplete pack file (will be removed): ef9a9e32d2841d0657acacefc859f1acaeb320011c600946632806be177ae32b
incomplete pack file (will be removed): fd96d91c45288709c0505656ca366df1fe7d68c119d6748cabd832abe05a9ff2
incomplete pack file (will be removed): fdb8a2c04b14b0e57cee91f594d7149a4d4122dbb9a0367afb37f4db31fa2ae5
repository contains 597373 packs (2150117 blobs) with 2.857 TiB
processed 2150117 blobs: 484 duplicate blobs, 707.676 MiB duplicate
load all snapshots
find data that is still in use for 25 snapshots
[0:44] 100.00%  25 / 25 snapshots
Fatal: [<data/3d56568f> <data/57181e75> <data/0e4ce059> <data/cc444c2f> <data/b2e379f9> <data/38f9a96b> <data/8132d9a4> <data/c573bcb9> <data/e4d8b94c> <data/3ec8733b> <data/901bcc03> <data/d9278c82> <data/dbcf2376> <data/d2a436a7> <data/33ba55e7> <data/2e3d7100> <data/8dd536f6> <data/f905ce2b> <data/1be0ac1a> <data/4bbe5a03> <data/c3200763> <data/1c0eafde> <data/d51d92b1> <data/4702c742> <data/013bac7a> <data/36258a6a> <data/511b80ed> <data/ec4f3f08> <data/3ef9832b> <data/d63c51e8> <data/dca1fee7> <data/5f082241> <data/d0463f6f> <data/dd32ba03> <data/76bb785d> <data/c746f890> <data/b4cb3746> <data/13703661> <data/d59b77d0> <data/5e226e55> <data/593b77a5> <data/58a9e264> <data/5ee6d6aa> <data/c3e0512e> <data/16017980> <data/2d5dfa95> <data/79d14056> <data/f70dadaa> <data/d9029400> <data/fe2558c8> <data/03fb9c4b> <data/0d077b94> <data/b82507b7> <data/6db121ae> <data/40a95358> <data/33a7b169> <data/947d9621> <data/43ed2189> <data/9cba2ff2> <data/f3cfdb69> <data/a4cbb0fe> <data/7a564ed3> <data/58518a68> <data/2becdeca> <data/abfe83ba> <data/e5645bc4> <data/0e7ee1ff> <data/4564d1e6> <data/fa4c4a9d> <data/9cfc7a10> <data/c6fccdad> <data/52195972> <data/bab427cb> <data/e4193f50> <data/ece7df04> <data/a57e94a7> <data/f9eb1c48> <data/c782cfaf> <data/94104234> <data/760366ae> <data/d38fa25c> <data/aa5caf50> <data/10db8281> <data/111031f5> <data/3f7e531c> <data/286aee98> <data/02d413a8> <data/e021d712> <data/09b591fe> <data/ccd60425> <data/c37d8a1f> <data/8e8626e7> <data/dd1758fd> <data/32a9c2e9> <data/3ba8e5a5> <data/fedadc33> <data/67be1c62> <data/97e0d088> <data/c5b65c04> <data/b2db64a3> <data/63b6f590> <data/3f7cde56> <data/158019e2> <data/cdc10a28> <data/76d7c237> <data/a8f44a72> <data/03251d90> <data/aa103e27> <data/e643d840> <data/aad7416f> <data/b94e06fe> <data/a6c9ec4f> <data/9d92d02a> <data/f56a50fb> <data/f2097e42> <data/edaff9e7> <data/fe9493bb> <data/991e99d2> <data/22e10578> <data/9d3a1480> <data/db8c2b66> <data/075bc94b> <data/651ebaf6> <data/b0a0cdc5> <data/2f21691e> <data/43b27c6b> <data/a49e26f1> <data/e3c57e8e>] not found in the new index
Data blobs seem to be missing, aborting prune to prevent further data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/choose
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
Backblaze B2

Expected behavior
-----------------
Prune to complete successfully without errors.

Actual behavior
---------------
Prune bails, with errors.

Steps to reproduce the behavior
-------------------------------
Run the above command on my repository.... No great, I know.

Do you have any idea what may have caused this?
-----------------------------------------------
None at all. I haven't had any power losses during backup, and a complete `restic check` and `restic rebuild-index` come back squeaky clean.

Do you have an idea how to solve the issue?
-------------------------------------------
No I don't.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
In general, I love restic. It's my backup tool, both at home and at work.

**Comment by MichaelEischer** [comment]
@adworacz I have a bunch of questions which could help with finding out what went wrong:

Do you know whether all still existing snapshots were created using the current restic version or also using an older one? So is this the first failing `prune` run? Do you have logs of the `backup` and `prune` run before the failing one? Did restic report any errors there? How often do you run `backup`, `check` and/or `prune`?

Is the repository used by multiple hosts or just a single host?
Was the repository always stored on B2 or did you create it locally and upload it to B2? I'm asking because the "incomplete pack file" shouldn't show up for B2.
Do you use the `unlock` command or is it called automatically from your backup scripts?

I'd like to investigate the incomplete pack files a bit:
`check` uses a temporary cache and freshly downloads files, so it won't see corrupted files by default in the repository's cache. Please run `restic check --with-cache` to check for cache corruption.

If that doesn't show errors:
- Please download the some of the files manually and run sha256sum on them. For example using `restic cat --quiet --no-cache pack 17ae81809bc5fb38b2d3d797d176a929c10eaedf4d9569b128f767127c8836f8 | shasum -a256`.
- Does `restic cat --quiet pack [...] | shasum -a256` return the same or a different result? This will let restic use a cached copy of the file if available. You could also look into the cache yourself (usually located at `~/.cache/restic/<repo_id>/`).
- Next, please use the Backblaze Web UI or a B2 client to get some metadata about the file. The most interesting would be creation time and modification time if available and the file size. Are there maybe several versions of the file?

It might also be helpful to know which snapshots are missing blobs: Please run `restic find --blob 3d56568f 57181e75 ...` (with the ids of the blobs reported as missing) to find the affected snapshots.

**Comment by adworacz** [comment]
## Update
Okay, general update and then I'll try my best to answer your questions.

After this failed `prune` I went ahead and did another `backup`. Interestingly, there were some errors in this backup that I haven't seen before. Here's an example:
```
...
error: parts of /mnt/data/example/file.txt not found in the repository index; storing the file again
...
```

Note that the files effected have been backed up multiple times before this, so I don't know if this was Backblaze losing data, my previous `forget` run causing issues somehow, or something else entirely.

In order to rule out bit rot, my data is (thankfully) stored on a BTRFS mirror array, so I ran a scrub over night. Scrub completed just fine with 0 errors, so something definitely happened to the Backblaze repo.

## Questions
1. Snapshots were created with a previous restic version (0.9.6 at the very least) as well as the current version (0.11.0).
2. This is the first failing `prune` run, kinda. I ran a `forget --prune` just a day ago which also failed, which is what alerted me to this issue. The failures in the past few days are the only failures I received. I only run prune manually, every few months or so.
3. I do not have logs from the previous backup/prune runs, unfortunately. This is highlighting how I should add log keeping to my setup.
4. I run `backup` every few weeks, manually. I generally don't run `check` ever, and as I state above, I only run `prune` every few months, manually.
5. The repository is only used by a single host.
6. The repository was always stored on B2.
7. I manually use the `unlock` command, I do not have it as part of my scripts.
8. I'm running `restic check --with-cache` now, as I type this. As noted above, I did run another `backup` yesterday with the errors I called out above, so maybe that will affect the outcome, not sure. UPDATE: that was fast, see below
9. Based on the output of that, I'll take the next steps you list (ie `restic cat --quiet ...`).
10. Once the check is finished, I'll try the `restic find --blob` command you mentioned.

### `restic check --with-cache` found errors
Welp, your `restic check --with-cache` command found errors (and much faster than I expected).

Here's a sample:
```
error for tree d0183959:
  tree d0183959: file "example.txt" blob 3522 size could not be found
  tree d0183959: file "example.txt" blob 3523 size could not be found
...
  tree d0183959, blob fd25bb95: not found in index
  tree d0183959, blob 03493c6d: not found in index
...
error for tree 078ecf06:
  tree 078ecf06: file "example.txt (yes same file)" blob 3522 size could not be found
  tree 078ecf06: file "example.txt" blob 3523 size could not be found
...
  tree 078ecf06, blob fd25bb95: not found in index
  tree 078ecf06, blob 03493c6d: not found in index
...
Fatal: repository contains errors.
```

**Comment by adworacz** [comment]
I'm running the `restic find --blobs` command now.

**Comment by MichaelEischer** [comment]
> error: parts of /mnt/data/example/file.txt not found in the repository index; storing the file again

The earlier `rebuild-index` probably has removed the pack files listed as incomplete. So restic now knows that certain blobs are missing and whenever `backup` (since restic 0.10.0) finds a file with missing blobs it will back up the file again to repair the missing blobs.

> `restic check --with-cache` found errors

I assume that the earlier `rebuild-index` couldn't access the pack files with the missing files and that these are thus now reported as missing. (Did you run `check` before or after `rebuild-index`?) It would be interesting to know whether the incomplete pack files reported earlier on are intact or not. Could you run `restic cat pack --quiet 2a34d963f6c706696335e1d4bda6741e01deeca162b8e983c7ecf2b542d73c94 | shasum -a256` on a few of the files reported as `incomplete pack file`? Please also run that command with an added `--no-cache` option for restic.

> I'm running the restic find --blobs command now.

That looks like a rather random collection of snapshots (it's much shorter after piping it through `sort -u`). Could you look at a few of the incomplete pack file in the B2 web ui and lookup their creation and modification time?

**Comment by adworacz** [comment]
Yessir, I’ll try all of the above tonight after work.

**Comment by adworacz** [comment]
1. I ran `check` (no `--with-cache`) before I ran `rebuild-index`, then I ran the second `check --with-cache`.
2. Output of `cat pack` on a few:
```
Warning: hash of data does not match ID, want
  2a34d963f6c706696335e1d4bda6741e01deeca162b8e983c7ecf2b542d73c94
got:
  e3ad258d40f8d8b386d127d030e39c666c9651bc029fbdb43fac94d4057321a5
e3ad258d40f8d8b386d127d030e39c666c9651bc029fbdb43fac94d4057321a5  -
```
```
These were fine:
003dec62564216e7819241c370154097d705b39c17e146ac5a6ba46f20913727 -
fd96d91c45288709c0505656ca366df1fe7d68c119d6748cabd832abe05a9ff2 -
17559ab4f99881b2cb2b2e5e38776f15e2afdfac1c20cb873aa34d15b276fecd -
```
3. Output of `cat pack --no-cache`:
```
Interestingly, this one was fine with --no-cache:
2a34d963f6c706696335e1d4bda6741e01deeca162b8e983c7ecf2b542d73c94  -
```
4. Backblaze "upload date" of `2a34d963f6c706696335e1d4bda6741e01deeca162b8e983c7ecf2b542d73c94` : `12/22/2019 16:42`

Since there seems to be a mixing of hash successes, I'm going to run a quick script to go through all the hashes, give me a second.

**Comment by MichaelEischer** [comment]
> Interestingly 2a34d963f6c706696335e1d4bda6741e01deeca162b8e983c7ecf2b542d73c94 is fine now, I presume because of the --no-cache run above, the cache is now updated?

When restic is run with `--no-cache` then restic doesn't use or modify the cache in any way. My guess would be that the `2a34d963[...]` pack file only contains data blobs and thus isn't cached at all. In that case the cache (usually located in `~/.cache/restic/06abe926[...]`) shouldn't contain that file at all. That looks a bit like the download problem was fixed somewhere else.

Could you use `cat pack --no-cache` (without the shasum part) again to download the pack files that still returned errors on the last try? Then please calculate the sha1 hash this time (not sha256) and please compare these to the sha1 hash these files are supposed to have according to the B2 web UI. I wonder whether any discrepancies will show up there. I suspect that the actual problem cause could be somewhere on the B2 side (see https://github.com/restic/restic/issues/3271#issuecomment-777004085).

**Comment by adworacz** [comment]
### cat pack --no-cache
`cat no-cache-packs.txt`

```
0a8fbcd5a0b7fcc2f31ecc3a2cad94857935b68bcea00be36b23d0f6230f2fa8
14671c360e4e0070ac534257f04ec2d9f54eaa726dc02e33c49c794335666b0e
1cd22f6b1ed9825eaf19ef14fd58f2741d0028bf94bd3939a3e3ed7e611f8c38
957b9ef669e0652276221cba51f61794020e43fc6792b4066c03e4767510d152
fd96d91c45288709c0505656ca366df1fe7d68c119d6748cabd832abe05a9ff2
```

`cat no-cache-packs.txt | xargs -n1 -I{} sh -c 'PATH=/home/adubadmin/bin/:$PATH backupVideo.sh cat pack --no-cache --quiet {} | shasum -a1 ' | tee restic-logs/no-cache-sha1sum.txt`

```
fc9adb959f582a6e5ac5656d2c4be9ff41b26138  -
00efd8cb01b7ca92d8fed2c2c18280944e597365  -
02aab081290c682314d7b799ac7ce672a01c52e4  -
Warning: hash of data does not match ID, want
  957b9ef669e0652276221cba51f61794020e43fc6792b4066c03e4767510d152
got:
  2d1c0443958a125f700ee26818185b39429c9d7b5ff43fd4a1c9d8c7c2d5025e
27c6f0ae849d0393d63894e3b027dcac8748ddef  -
5368e2ccce4602191ae600cff91055c3528028c5  -
```

(You'll note that `957b9ef669e0652276221cba51f61794020e43fc6792b4066c03e4767510d152` has a different hash than the previous run...)

### Backblaze sha1sums
In the same order as above:
```
fc9adb959f582a6e5ac5656d2c4be9ff41b26138
00efd8cb01b7ca92d8fed2c2c18280944e597365
02aab081290c682314d7b799ac7ce672a01c52e4
53e67f7f0f4ac099cbfa8ad90710809fcd96fd6e <-- Note this is the problem child above
5368e2ccce4602191ae600cff91055c3528028c5
```

**Comment by adworacz** [comment]
At this point, it seems the next course of action is to open a ticket with Backblaze, as they really seem to be the ones at fault here. I ran some of the sha1 checks again and different packs are failing, meaning it's non-deterministic. 

I can't think of any reason for that outside of it being Backblaze's fault.

**Comment by kmwoley** [comment]
I'm seeing a similar, non-deterministic behavior with Backblaze. Started happening about a week+ ago. #3268

**Comment by adworacz** [comment]
I opened a ticket with Backblaze, and they got back to me this morning. Apparently they're working with Restic developers on diagnosing the issue. I hope to assist them with any data I can.

**Comment by adworacz** [comment]
I just finished a fresh `backup` using version 0.11.0, and there were no errors to speak of. Granted this was a backup, so I didn't expect any major errors since I haven't done a `rebuild-index` or similar, like I did above when the backup found issues.

I'm going to upgrade to 0.12.0, and run similar `cat pack` checks again to see how things are.

**Comment by adworacz** [comment]
Completed the `cat pack --no-cache | shasum -a` scan, which started at 5:46PM Pacific, and I had zero issues found. All checksums were calculated correctly.

I'm going to try running a `prune` again, now that things seem to be behaving better.

**Comment by adworacz** [comment]
### `prune` still failing
```
loading indexes...
loading all snapshots...
finding data that is still in use for 30 snapshots
[0:16] 100.00%  30 / 30 snapshots

searching used packs...
{<data/00d68978> <data/0181e92f> <data/03493c6d> <data/03f5649d> <data/0511a4aa> <data/055216f6> <data/065c7cd2> <data/08255409> <data/08e6c1af> <data/08e982fb> <data/0af3f173> <data/0cde9f9e> <data/0cef28ca> <data/0e3cb05f> <data/0e8634a6> <data/1086d25a> <data/11943c8c> <data/1213469d> <data/12afede0> <data/14a6d509> <data/15ffdd65> <data/168abfad> <data/17c4d339> <data/1a4be07d> <data/1c5b27f7> <data/1c5d1b39> <data/1df34038> <data/1fae43b7> <data/20881654> <data/2185d5eb> <data/288a805d> <data/2a12643a> <data/2b35c26e> <data/2c9b35dd> <data/2d200dd0> <data/2e708683> <data/2e837148> <data/2f420983> <data/314eeb3c> <data/318e3419> <data/32a9c2e9> <data/32cd8b85> <data/33ec7752> <data/3572bea6> <data/368cf107> <data/37e3cafe> <data/3c3bfb3e> <data/3e884db1> <data/3eacaf4e> <data/3eec8d16> <data/4050d976> <data/40803017> <data/40d417a4> <data/41a7bbe8> <data/42659fc1> <data/44c48011> <data/456032fe> <data/4595c96d> <data/45c427f1> <data/4708cffa> <data/481b3ec1> <data/48d509c2> <data/497fe629> <data/4b78d397> <data/4ced9bc5> <data/51f101db> <data/52f80e70> <data/533e2153> <data/542d14da> <data/543458ec> <data/5668443e> <data/5796df3c> <data/58d97a34> <data/59ea52ac> <data/5aff5ed1> <data/5b62138a> <data/5c4439b1> <data/5f3d906a> <data/61a06d79> <data/62c6e424> <data/63bf1932> <data/6629d6cb> <data/67e68d78> <data/67f591ee> <data/683d77bf> <data/6b3e9051> <data/6bbdeee4> <data/6bf4d1fb> <data/6c5188f8> <data/6c858073> <data/6dce8f13> <data/6f002000> <data/706ab205> <data/7165fd22> <data/71b6bdd7> <data/71c2d1df> <data/721666e8> <data/728c53b1> <data/728f4c8a> <data/759cd3cf> <data/75acf38b> <data/75b218eb> <data/785e3106> <data/78f18eda> <data/79bda805> <data/79da89fb> <data/7abdf84d> <data/7b5c021c> <data/7b70b080> <data/7c04687a> <data/7cd7ac66> <data/7d47564b> <data/7e54579b> <data/7e8886a9> <data/81646d21> <data/81ab185a> <data/8322a64a> <data/83694af7> <data/87f28afd> <data/89217eb2> <data/89c6a426> <data/8a179591> <data/8a47b4e7> <data/8ac8dadb> <data/8d6385d0> <data/8fd03c67> <data/907921b2> <data/91f56bee> <data/92311c52> <data/933e51b2> <data/93bf651e> <data/940fd763> <data/948db346> <data/94fc280f> <data/95bae00b> <data/965018d3> <data/977f34b3> <data/98a23ef3> <data/9a4889b0> <data/9b5c4af7> <data/9b7dc9f1> <data/9c93f93a> <data/9ce77e97> <data/a02bd947> <data/a3e930e5> <data/a4cbb0fe> <data/a5bddd2a> <data/a5ce406a> <data/a716f26a> <data/a76560cb> <data/ae4c8708> <data/aee4daff> <data/af5c3497> <data/b0a0cdc5> <data/b0c47d0c> <data/b305b8c1> <data/b3719c63> <data/b544865d> <data/b74c33ca> <data/b77d0c63> <data/b8954931> <data/bbe5098c> <data/bd6da8b6> <data/c0c54395> <data/c26318fa> <data/c7b6e29f> <data/c7e7144b> <data/cb9bb618> <data/cc5d0384> <data/cc85a6f9> <data/cda3c6de> <data/ce34bb4e> <data/d2b03d51> <data/d50daef7> <data/d5de6266> <data/d72d1315> <data/d8756f08> <data/d9a8be3f> <data/d9fd8076> <data/da29dc84> <data/daaee023> <data/db8c2b66> <data/dbc062fb> <data/dd1bfc8b> <data/df299e53> <data/e7eafbdc> <data/e819eb6c> <data/e8959991> <data/e8b9fffc> <data/eb45b4b3> <data/ec10c6b5> <data/ed6d742a> <data/ed78cc27> <data/efec5ada> <data/f04020b1> <data/f06875a2> <data/f0b96862> <data/f10f3ce3> <data/f2097e42> <data/f27f1d65> <data/f3bde017> <data/f47097f5> <data/f502bdce> <data/f5fe3b54> <data/f71db1d2> <data/f73852be> <data/f92b184d> <data/f9ad79a1> <data/f9e92ef6> <data/fa464833> <data/fb153e6f> <data/fbbf9d34> <data/fd25bb95> <data/fdc49437> <data/ff92a309> <data/fff5bc38>} not found in the index

Integrity check failed: Data seems to be missing.
Will not start prune to prevent (additional) data loss!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new/chooseFatal: index is not complete
```

### `check --with-cache` states repository contains errors
Lots of errors like:
```
...
tree e07c4334: file "example.txt" blob 318e3419dfadcb91ad260de5f1c2a41929840ceed4fb7b09e4b08b2e475784db not found in index
...
```

I'm running a quick `find --blobs` now just to double check.

**Comment by adworacz** [comment]
## Update
Based on the latest communications from Backblaze, I re-ran my `prune`. Still saw errors about "data seems to be missing", but I didn't end there.

After a `rebuild-index` (which is WAY faster in 0.12, I mean damn), I was able to do a `forget --prune` without any issues whatsoever.

So, as things stand, it appears that a `rebuild-index` was all that was required after the Backblaze issue was addressed (although I do see comments on other threads that indicate we might not be fully out of the woods yet).

As things are, I consider my issue resolved.

Feel free to close (I've left open to give repo contributors a chance to evaluate).

**Comment by MichaelEischer** [comment]
@adworacz Nice to hear that the issue has been resolved for you. I don't recall seeing anything in the issue that requires a fix in restic. After all if the backend returns broken data, then we're out of luck. So I'm closing this issue.

**Comment by vsuontam** [comment]
I am still seeing lots of these issues when using Backblaze with prune. Was this confirmed to be a Backblaze issue in the past?

Here is a sample of my prune output:

Remove(<data/7267cecbf1>) returned error, retrying after 485.170407ms: Delete: b2_delete_file_version: 400: File not present: data/72/7267cecbf1f9df720cf182a77f8ce9bcf4eab312dc859d53f6d5864ec6a72214 4_z1fee766953e756af7acf0d15_f117e9a35e3be47b2_d20220422_m181239_c001_v0001165_t0040_u01650651159530
b2_download_file_by_name: 404: : b2.b2errdeleted...
Remove(<data/f4da7f8f9a>) returned error, retrying after 625.193692ms: Delete: b2_delete_file_version: 400: File not present: data/f4/f4da7f8f9af85bfad06fe5a60fc3b3c637c55addbba7fe81dce3317d6aa78975 4_z1fee766953e756af7acf0d15_f1045f6585701de4e_d20220422_m151759_c001_v0001165_t0031_u01650640679854
b2_download_file_by_name: 404: : b2.b2errdeleted...
Remove(<data/033423e537>) returned error, retrying after 680.391926ms: Delete: b2_delete_file_version: 400: File not present: data/03/033423e53779220bff4bdfa3c3666c5788175f152a806ce7b7bc6ef17df36ae8 4_z1fee766953e756af7acf0d15_f11202c37bc097d7f_d20220125_m034029_c001_v0001165_t0002
b2_download_file_by_name: 404: : b2.b2errdeleted...
Remove(<data/dfb4935bc3>) returned error, retrying after 520.819355ms: Delete: b2_delete_file_version: 400: File not present: data/df/dfb4935bc31bdc9b45d2bc13b99f5c2b99a9cd18868dff8efe811f7a696e3bec 4_z1fee766953e756af7acf0d15_f1045f65857010f4f_d20220422_m140001_c001_v0001165_t0057_u01650636001684
b2_download_file_by_name: 404: : b2.b2errdeleted...
Remove(<data/77da6d16a3>) returned error, retrying after 723.864006ms: Delete: b2_delete_file_version: 400: File not present: data/77/77da6d16a310482cfc341448402e70f590db13585207495d52b83d95cec35deb 4_z1fee766953e756af7acf0d15_f1045f658570390c8_d20220422_m174634_c001_v0001165_t0020_u01650649594149
b2_download_file_by_name: 404: : b2.b2errdeleted...
Remove(<data/bc8961d135>) returned error, retrying after 548.638399ms: Delete: b2_delete_file_version: 400: File not present: data/bc/bc8961d135ab15287a4d1ec9098cd77f8022f968cc6d558b4812f96b4ff20614 4_z1fee766953e756af7acf0d15_f11202c37bc09c85a_d20220125_m041351_c001_v0001165_t0021
Remove(<data/60e1b8e337>) returned error, retrying after 286.646999ms: Delete: b2_delete_file_version: 400: File not present: data/60/60e1b8e337d582b1873ea35ae59cb163fda916e7680ff54855759b42d1031207 4_z1fee766953e756af7acf0d15_f1045f65857001818_d20220422_m122331_c001_v0001165_t0011_u01650630211624
b2_download_file_by_name: 404: : b2.b2errdeleted...
b2_download_file_by_name: 404: : b2.b2errdeleted...
Remove(<data/b84f85c81d>) returned error, retrying after 593.198002ms: Delete: b2_delete_file_version: 400: File not present: data/b8/b84f85c81db65e5078c722f1db0819b9e0df30f2f171904f2aa61e0f7145f6ad 4_z1fee766953e756af7acf0d15_f117e9a35e3be1e45_d20220422_m175851_c001_v0001165_t0017_u01650650331377
b2_download_file_by_name: 404: : b2.b2errdeleted...
[13:30:35] 66.65%  581087 / 871884 files deleted...

**Comment by MurphySunset** [comment]
I'm running into a similar problem with a (large, 4tb) b2 repo.

Trees and blobs are missing since a few days. When running `restic backup`: `error: tree 4515b184c69f798cb0e8429aed6d4efbac0e44ef21aaf1122ae867a77fbd636b could not be loaded; the repository could be damaged: decrypting blob 4515b184c69f798cb0e8429aed6d4efbac0e44ef21aaf1122ae867a77fbd636b failed: nonce is invalid` (I have hundreds of lines like this one).
I tried removing a few snapshots referencing a given blob but they look like 6 month old blobs so they're might be referenced in too many snapshots and it bugs me a lot to remove that much data history.

`restic check` and `restic forget --prune` are running fine though.

I think that this is a b2 issue, I consider getting in touch with them but how can I prove them that the issue is on their side?

**Comment by MichaelEischer** [comment]
@MurphySunset "nonce is invalid" means that the nonce field consists only of zero bytes. So yes that could be a problem at the B2 side. 

> `restic check` and `restic forget --prune` are running fine though.

`--prune` only has an effect if some snapshots were actually deleted. As `check` runs correctly, please try to remove the local cache of restic (see `restic cache` for the location), which might be corrupted.

If that doesn't help try the following horrible construction to find out which pack file contains the problematic blob (based on https://github.com/restic/restic/issues/1999#issuecomment-424333904):
```shell
restic list index | while read idxid; do \
         restic cat index $idxid | jq '.packs | map(select(.blobs | map(select(.id | contains("0251d25ca5bebde32fdf9d947420ccbafb5529dc99cbd3a4f3a7545378c26ee2"))) | .[0] )) | map(.id)'; \
done
```

Then download the pack file using `restic cat pack $id`, `restic cat pack --no-cache $id`. Also try to locate the file using the web interface (it is stored in `data/<first two bytes>/<full id>`.
