### ISSUE TITLE
Restic restore --files-from feature

### ISSUE THREAD

**Issue by ahmed658** [restic/restic#4867]
Output of `restic version`
--------------------------
restic 0.16.4 compiled with go1.21.6 on linux/amd64

What should restic do differently? Which functionality do you think we should add?
----------------------------------------------------------------------------------
It would be helpful if the --files-from feature that exists in "backup" function to backup a list of files saved as paths in a text file also existed for the "restore" function to restore a list of files based on their paths that are read from a text file and restored from a snapshot to a target location.

What are you trying to do? What problem would this solve?
---------------------------------------------------------
This would allow me to create a list of files paths in a snapshot using the restic "ls" function and save the output list to a text file, then filter those files to wanted ones to restore daily from the latest snapshot using a restore script.
This can somehow already be achieved by the recently added restic "--include-file" option to the "restore" function but the --include and --exclude expect patterns not plain file names and that causes a problem when trying to restore files which have pattern interpretable characters in their paths like "WR-7200o[.jpg" for example.

Did restic help you today? Did it make you happy in any way?
--------------------------
I use it in all my production servers and by far it's the most efficient, fast, yet reliable backup solution that we have worked with. I genuinely can't give the developers enough praise for their efforts in creating a production-ready and reliable open-source backup solution that's actively maintained and improved more than even the other proprietary solutions out there.

**Comment by konidev20** [comment]
I am thinking there can be a flag called `--includes-file-verbatim`, it will not process regular expressions or trim whitespaces? This will ensure the exact paths output from the `restic ls` command will be used.

**Comment by MichaelEischer** [comment]
In that case it probably should be called `--files-from-verbatim` just like the option used by the `backup` command. The main question is whether there's another way to not add tons of new options to the `restore` command (there are already 8 include/exclude options by now).

**Comment by konidev20** [comment]
Hey @MichaelEischer, 

I gave this some thought, my idea is that we can reduce the number of flags to `--includes`, `--includes-file`, `--excludes`, `--excludes-file`. This can be achieved by introducing a as to how the pattern must be processed. The prefixes would be `i` for insensitive matching and `v:` for verbatim. 

Note: This can be done while preserving backwards compatibility. The redundant flags will still be usable, but can be marked deprecated and removed based on discussion. 

How this would look in a command:
```
restic restore --target /some/path --include "i:*.log" --include "*.txt" --include-file "i:/path/to/inclusion-file", --include-file "v:/path/to/files-from-verbatim"
```
`--include "i:*.log"` will do an case insensitive pattern matching for `.log` files
`--include "*.txt"` will do a case sensitive pattern matching for `.txt` files
`--include-file "i:/path/to/inclusion-file"` will be equivalent to `--iincludes-from-file`
`--include-file "v:/path/to/files-from-verbatim"` will be equivalent to a file `--files-from-verbatim`

This design can be extended to the backup command as well.

**Comment by MichaelEischer** [comment]
> flags to `--includes`, `--includes-file`, `--excludes`, `--excludes-file`.

I'm confused. Did you mean `--include` or actually `--includes`? colons `:` are perfectly valid parts of filenames on unixoid systems, similarly `--include-file i:/path` will cause problems on Windows.

`--pattern` as used by borg might be more suitable, see [docs](https://borgbackup.readthedocs.io/en/stable/usage/help.html#borg-help-patterns) for more details. That might even allow unifying includes and excludes. Although that probably requires a lot more thought to get it working.

**Comment by konidev20** [comment]
> Did you mean --include or actually --includes

I meant `--includes`.

> colons : are perfectly valid parts of filenames on unixoid systems, similarly --include-file i:/path will cause problems on Windows.

Yes, I figured this. I was thinking of another approach. 

> --pattern as used by borg might be more suitable, see [docs](https://borgbackup.readthedocs.io/en/stable/usage/help.html#borg-help-patterns) for more details. That might even allow unifying includes and excludes. Although that probably requires a lot more thought to get it working.

I will check this out next.

**Comment by deajan** [comment]
With restic, we got `--iinclude` to have case insensitive includes.
Is there perhaps a way to get `--vinclude` and `--viinclude` to get verbatim includes without square brackets interpretation ?

**Comment by MichaelEischer** [comment]
The `restore` command already has 8 include and exclude options (not counting the xattr ones). So we really need to use some unified options instead of adding even more into the mix. Simply adding `verbatim` options would outright double the number of options, which is out of the question.

Please also take a look at what other backup tools like for example borgbackup do. Maybe the way to go is to add some new option `--include-pattern type:pattern` where we can simply integrate different pattern types.

> The prefixes would be `i` for insensitive matching and `v:` for verbatim.

When adding such prefixes to the existing options, those would conflict with filenames on unix and volumes on windows.

**Comment by chewi** [comment]
I really want to work on this since finding that including thousands of files has a _massive_ impact on performance. It has to find the parent snapshot for each individual file.

I don't think Borg's approach is the way to go. Prefixing each line is totally different to what restic does now. You'd still need separate options for file vs inline and raw vs not.

There are literally no safe characters you can use in an argument prefix. Maybe it doesn't need to be completely watertight though. It's already the case that we use `!` in exclude files even though that is a valid path character. I haven't checked whether it can be escaped. I'll have a think.

**Comment by chewi** [comment]
An initial idea…

Maybe prefixing each line isn't so bad, but let's keep compatibility with the existing format. It is the same as gitignore, so quite well understood.

I think double colon might work as a prefix. It's not valid in Windows. It is valid in Unix but unlikely to conflict in practise. Maybe I can allow it to be escaped. Note that gitignore supports escapes.

Example file:
```
/traditional/entry
!/traditional/negative/entry
iv::/case/insensitive/and/verbatim/entry
i::!/negative/entry
v::C:\some\windows\entry
```

Example args:
```
--exclude "/traditional/entry"
--exclude "iv::/case/insensitive/and/verbatim/entry"
--exclude-file "/traditional/file"
--exclude-file "iv::/case/insensitive/and/verbatim/file.txt"
--exclude-file "0v::/null/separated/verbatim/file.txt"
--exclude-file "v::C:\some\windows\file.txt"
```

I don't think null-terminated (raw) needs to imply verbatim. You could still have null-terminated patterns. The `0` option therefore wouldn't make sense as a line prefix.

I thought about just having `--exclude` and `--include` with an `f` option to signify a file rather than a single entry, but I think that makes things needlessly complicated and breaks compatibility.

I also thought about having a prefix with nothing afterwards to mean "set these as default from this line", but that wouldn't fit well with (v)erbatim. Best keep it simple.

I'm assuming you currently can't use `!` in an include rule.

This could be expanded with other options later like `r` for regular expression matching, but I'm not personally interested in that.

If single character options will get confusing, maybe we could separate them with commas or something, but I hope we wouldn't need _that_ many.

Thoughts?

**Comment by chewi** [comment]
FYI I've made a rough start, but it's a little tricky because it's at odds with the existing code structure.

I realised it might make sense to have an inverse option for (i)nsensitive. Maybe `I`? I'm not sure if that's better than (s)ensitive.

**Comment by MichaelEischer** [comment]
Just a few remarks (I haven't spent much time thinking about this so far):
Some multi-character prefix like `re:`, `glob:`, `iglob:` etc. would also work and be far more self-explanatory. AFAIK there are no multi-character volume names on windows. If these prefixes would collide with some filename, then one simply has to explicitly specify a prefix to avoid ambiguity.

> --exclude-file "0v::/null/separated/verbatim/file.txt"

Are those prefixes really necessary? They feel rather weird and also break autocompletion.

> I really want to work on this since finding that including thousands of files has a massive impact on performance. It has to find the parent snapshot for each individual file.

That's actually a different problem than unifying include and exclude options. A better way to let restic known which snapshots actually belong together, even if the file list changes, is tracked in https://github.com/restic/restic/issues/4026 .

**Comment by chewi** [comment]
I did consider multi-character prefixes, but how to combine them? Commas? More colons? Probably commas.

With that, I guess a single colon would work just as well as a double.

> Are those prefixes really necessary? They feel rather weird and also break auto-completion.

I was under the impression that file-wide options with fewer arguments was the main goal here, with per-line options possibly being a bonus. You gave the `--include-pattern type:pattern` example above, but I guess that wasn't for a file. You seemed to suggest you didn't want `--exclude-file-raw`, but how would you apply raw to an exclude file otherwise? Options on the first (commented) line of the file might work, but it doesn't feel right to me.

I'm not an expert on auto-completion, but I gather Bash is smart enough to still complete a path if you tell if to strip the prefix. Are you concerned about PowerShell?

> That's actually a different problem than unifying include and exclude options.

Interesting. I'm not sure if that's quite the same case, as I used `--files-from-raw` without any path arguments, but fixing these excludes would allow me to pass `/`, which should resolve the issue for me.

**Comment by chewi** [comment]
I would appreciate more direction here, as I don't have strong opinions on the approach, and it's ultimately your call. I have found restic to be very intuitive overall, so I really want to do it justice and get this part right.

I'm usually spread very thin, so please make the most of my attention while you have it. 🙂

**Comment by chewi** [comment]
Since you didn't decide on the best approach, I implemented just what I needed in #5714. Take it or leave it.

**Comment by mayerwin** [comment]
This is still an issue, I've opened #21872 proposing `--include-from-raw` on `restore` (and `rewrite`, via the shared `IncludePatternOptions`) as a direct mirror of `backup --files-from-raw` (#3017). The file holds NUL-terminated absolute paths, each matched literally against the snapshot tree; glob metacharacters (`*`, `?`, `[`, `]`, `**`) lose their special meaning, so paths like `WR-7200o[.jpg` from this issue's example round-trip cleanly.

The Windows case from #5565 (closed as duplicate here) is the strongest motivation, Go's `filepath.Match` treats `\` as a path separator on Windows, AND `ValidatePatterns` rejects the POSIX class self-escape `[[]` / `[]]` as invalid, so a literal `[` or `]` is currently unrepresentable in any `--include` pattern on Windows. There is no workaround there short of broadening the pattern with a wildcard and over-restoring every same-prefix sibling, wasted bandwidth, disk, and energy for callers that already have exact paths.

The PR is strictly additive: no existing glob semantics change, no existing test was modified. It composes with `--include` / `--iinclude` / `--include-file` (union semantics).

**Comment by moltenform** [comment]
I'm blocked on this bug, for `--exclude-file`. When on Windows, I can't refer to a file with a `[` character. Escaping with `\[` or with `[[]` does not work.
