### ISSUE TITLE
Support for amazon acceleration endpoint

### ISSUE THREAD

**Issue by mtfelian** [restic/restic#707]
## Output of `restic version`
```
restic 0.3.1 (v0.3.1-2-g75f21f2)
compiled at 2016-12-15 17:18:53 with go1.6.3 on linux/amd6
```

## Expected behavior
When using restic to backup or restore to Amazon S3 Accelerated Endpoint, we receive a following error: ```
unable to open repo at s3:name.s3-accelerate.amazonaws.com/name: minio.New: Amazon S3 endpoint should be 's3.amazonaws.com'.
```
here is the environment variable: 
```
export RESTIC_REPOSITORY=s3:name.s3-accelerate.amazonaws.com/name
```
## Actual behavior
Correct working. 

## Steps to reproduce the behavior
1. Enable acceleration in S3 Amazon Control Panel. 
2. Set RESTIC_REPOSITORY env to accelerated endpoint. 
3. Try to work with it.

**Comment by fd0** [comment]
Thanks for your report. We're using the [minio s3 Go library](https://github.com/minio/minio-go) to access S3. It expects `s3.amazonaws.com` as the host name for accessing data on S3, if a bucket was created in another region, it follows the redirect from the Amazon servers. I'm raising an issue there.

**Comment by mtfelian** [comment]
I tries to pass into env value like `s3:http://......:80` due to Restic documentations permits this. But i received the same error, so it can be supposed that it will not work with anything except Amazon standart endpoint.

**Comment by fd0** [comment]
The documentation states that this form can be used "For an S3-compatible server that is not Amazon". If you use it with an Amazon URL, that won't work and you get the error.

The great people from Minio are working on supporting Amazon Acceleration Endpoints, that's tracked here: https://github.com/minio/minio-go/issues/585

**Comment by mtfelian** [comment]
Thanks!

**Comment by etix** [comment]
Fixed upstream: https://github.com/minio/minio-go/issues/585#issuecomment-270563165

**Comment by dlitz** [comment]
Bump. I'm still getting this error when using a repository like `s3:mybucket.s3-accelerate.amazonaws.com/mybucket/folder`

`Fatal: unable to open config file: Stat: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'`

This is with the restic 0.9.1 released binary (Linux amd64).

**Comment by fd0** [comment]
That's expected: while an accelleration endpoint is now supported in minio-go, no code for using it has been added to restic. If someone is up for a PR (and can test this!) I'd be willing to help reviewing and getting a PR merged. Until that happens, it won't be supported by restic :)

**Comment by MichaelEischer** [comment]
If someone is up for a PR, please take a look at https://github.com/minio/mc/pull/1946/files for an example implementation.
