### ISSUE TITLE
Frequent i/o timeout with S3 backups

### ISSUE THREAD

**Issue by TamalSaha** [restic/restic#881]
Hi,
I have been testing restic 0.5.0 to backup my desktop into S3. I have a max upload BW of 1.5 MB/s. I noticed that when I try to backup any folder that is more than several hundred MB, I get i/o timeouts. Here are some examples:

```sh

$ ./restic -r s3:s3.amazonaws.com/tigerworks1 backup ~/go/src/github.com/bndr
enter password for repository: 
scan [/home/tamal/go/src/github.com/bndr]
scanned 148 directories, 282 files in 0:00
[0:02] 100.00%  315.404 KiB/s  630.810 KiB / 630.810 KiB  430 / 430 items  0 errors  ETA 0:00 
duration: 0:02, 0.21MiB/s
snapshot 61d842ec saved

$ ./restic -r s3:s3.amazonaws.com/tigerworks1 backup ~/go/src/github.com/appscode-ci/
enter password for repository: 
scan [/home/tamal/go/src/github.com/appscode-ci]
scanned 569 directories, 2548 files in 0:00
panic: client.PutObject: Put https://tigerworks1.s3-us-west-2.amazonaws.com/restic/data/01517dcb5a8e4bce09cf58dd83fae697610aa726c50a29dc39940da7adae63aa: dial tcp: lookup tigerworks1.s3-us-west-2.amazonaws.com on 127.0.1.1:53: read udp 127.0.0.1:60209->127.0.1.1:53: i/o timeout

goroutine 2432 [running]:
restic/archiver.(*Archiver).saveChunk(0xc4203135e0, 0x3d00d59, 0x65fb1f, 0x1f57c761100000, 0xc44727a000, 0x65fb1f, 0x75e000, 0xc420296000, 0xb3c040, 0xc42000c098, ...)
	/tmp/restic-build-152363142/src/restic/archiver/archiver.go:163 +0x270
created by restic/archiver.(*Archiver).SaveFile
	/tmp/restic-build-152363142/src/restic/archiver/archiver.go:237 +0x381
```

My questions are:
- If I just retry will that result in safe backups?
- Can restic retry itself, to handle these type of intermittent i/o issues over public internet?

Thanks.

**Comment by fd0** [comment]
Thanks for taking the time to report this.

> My questions are:
> - If I just retry will that result in safe backups?

Yes.

> - Can restic retry itself, to handle these type of intermittent i/o issues over public internet?

It's planned to add retry logic for all backends, but that's not done yet.

Another user privately reported a similar issue yesterday with the `prune` operation having timeouts on s3. They reported that commenting out [this line](https://github.com/restic/restic/blob/debug-s3-connections/vendor/src/github.com/minio/minio-go/api.go#L616) in the `minio-go` library we're using for accessing s3 mitigates the problem. Could you try that and report back?

Ping @harshavardhana, could you please have a look? Do you also see this?

**Comment by harshavardhana** [comment]
> Ping @harshavardhana, could you please have a look? Do you also see this?

@fd0 strange but we can definitely remove it.. if it causes persistent issues.

**Comment by trbs** [comment]
@fd0 @harshavardhana I don't think commenting out [this line](https://github.com/restic/restic/blob/debug-s3-connections/vendor/src/github.com/minio/minio-go/api.go#L616) completely mitigated the issue. More the other way around; I think that line makes the timeouts in AWS more visible since (for me) it adds a `Connection: close` header to every response. Thus having a higher chance of getting a connection to S3 that does not get past the SYN_SEND stage of the handshake. (which I observed every time I get a timeout from AWS S3)

Also this [PR](https://github.com/restic/restic/pull/883) helped me further by significantly lowering the number of http calls (specifically `HEAD` calls) needed for `prune` to AWS although that might not be much help for this issue.

**Comment by harshavardhana** [comment]
> @fd0 @harshavardhana I don't think commenting out this line completely mitigated the issue. More the other way around; I think that line makes the timeouts in AWS more visible since (for me) it adds a Connection: close header to every response. Thus having a higher chance of getting a connection to S3 that does not get past the SYN_SEND stage of the handshake. (which I observed every time I get a timeout from AWS S3)

Time-outs in general are quite common with S3 only way to do is perhaps to retry properly and let it fail after few attempts which minio-go already does in binomial fashion. Will check if we retry errors like net.Dial timeout etc.

> panic: client.PutObject: Put https://tigerworks1.s3-us-west-2.amazonaws.com/restic/data/01517dcb5a8e4bce09cf58dd83fae697610aa726c50a29dc39940da7adae63aa: dial tcp: lookup tigerworks1.s3-us-west-2.amazonaws.com on 127.0.1.1:53: read udp 127.0.0.1:60209->127.0.1.1:53: i/o timeout

From the error message the IP should be 54.x.x and not sure why its 127.0.1.1 and also why there is a UDP request . @fd0

**Comment by trbs** [comment]
Was wondering about 127.0.1.1 and the UDP request as well :)  Mine look like:

```
restic  18151 restic    3u     IPv4 3416644      0t0   TCP aaa.bbb.ccc.ddd:40576->52.216.224.48:https (SYN_SENT)

Get https://xxx.s3.amazonaws.com/xxx/data/8b4c81283439356d587135d4ce1fff2fd1c43d4373b5a85eeca2f9e64583ef7b: dial tcp 52.216.224.48:443: getsockopt: connection timed out

or

Head https://xxx.s3.amazonaws.com/xxx/data/82d47af3c36a9226ef279f22d12d8549f437a072bb38d25bbf46590527fe99f2: dial tcp 52.216.224.112:443: getsockopt: connection timed out
```

**Comment by TamalSaha** [comment]
I was using a bucket in Oregon region, with addr s3:s3.amazonaws.com/tigerworks1 . Is that a problem?

**Comment by harshavardhana** [comment]
> restic  18151 restic    3u     IPv4 3416644      0t0   TCP aaa.bbb.ccc.ddd:40576->52.216.224.48:https (SYN_SENT)
> 
> Get https://xxx.s3.amazonaws.com/xxx/data/8b4c81283439356d587135d4ce1fff2fd1c43d4373b5a85eeca2f9e64583ef7b: dial tcp 52.216.224.48:443: getsockopt: connection timed out
> 
> or
> 
> Head https://xxx.s3.amazonaws.com/xxx/data/82d47af3c36a9226ef279f22d12d8549f437a072bb38d25bbf46590527fe99f2: dial tcp 52.216.224.112:443: getsockopt: connection timed out

Yes this is the expected style we have seen this many times and happens all the time.  Let me check if we do retry on these properly.  Thanks @trbs

**Comment by trbs** [comment]
@TamalSaha Looks like it's the DNS request (UDP) that is timing out on 127.0.1.1:53 not S3 itself as in my case.

Maybe you could try with using 8.8.8.8 and 8.8.4.4 in /etc/resolv.conf and see if that helps for you ?

**Comment by TamalSaha** [comment]
I use comcast internet in Eastbay, SF. I already use 8.8.8.8. My desktop connected to router that is connected to comcast modem. I think pretty standard setup.
![netcfg](https://cloud.githubusercontent.com/assets/94814/23931965/5602ae9c-08f2-11e7-8954-e282c0f15d6d.png)

I am confused as you are regarding these DNS errors.

**Comment by fd0** [comment]
DNS errors may occur when there are not enough file descriptors available (then sending a UDP packet fails), this may happen for example when there's a file descriptor leak in restic or in one of the libraries we use. We had that in the past (in restic's code base), and I was certain that the problem was properly addressed. Hm.

**Comment by harshavardhana** [comment]
> panic: client.PutObject: Put https://tigerworks1.s3-us-west-2.amazonaws.com/restic/data/01517dcb5a8e4bce09cf58dd83fae697610aa726c50a29dc39940da7adae63aa: dial tcp: lookup tigerworks1.s3-us-west-2.amazonaws.com on 127.0.1.1:53: read udp 127.0.0.1:60209->127.0.1.1:53: i/o timeout

i/o timeout is retried properly.  Adding support for retrying `getsockopt: connection timed out`

**Comment by sanmai** [comment]
You could be out of file descriptors for reasons beyond restic's control. Just saying.

**Comment by TamalSaha** [comment]
Hi,
I ran the process again and got the same :53 i/o timeouts. This is what I see:

```bash
$  ulimit -n
1024
$  ulimit -Hn
65536
$ ulimit -Sn
1024

# 16512 was the pid, so
$ cat /proc/16512/limits
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             62853                62853                processes 
Max open files            1024                 65536                files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       62853                62853                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        
```

**Comment by fd0** [comment]
@TamalSaha Can you please try running the backup again and watch `/proc/PID/fd` during execution? e.g. with:
```
$ while true; do date; ls /proc/$(pgrep restic) | wc -l; done
```

**Comment by TamalSaha** [comment]
I tried it again. Same error. Here is the log:

```sh
# while true; do date; ls /proc/$(pgrep restic) | wc -l; sleep 5; doneThu Mar 16 16:22:47 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:22:52 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:22:57 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:23:02 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:23:07 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:23:12 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:23:17 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:23:22 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:23:27 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:23:32 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:23:37 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:23:42 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:23:47 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:23:52 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:23:57 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:24:02 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:24:07 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:24:12 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:24:17 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:24:22 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:24:27 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:24:32 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:24:37 PDT 2017
ls: cannot access '27241': No such file or directory
49
Thu Mar 16 16:24:42 PDT 2017
48
Thu Mar 16 16:24:47 PDT 2017
```

**Comment by fd0** [comment]
Ok, that looks reasonable. Very strange.

**Comment by TamalSaha** [comment]
@fd0, does this look relevant? https://github.com/docker/kitematic/issues/718#issuecomment-229512078

**Comment by fd0** [comment]
Hm, not really. That's about dns lookups via tcp, yours seem to be standard udp (according to the error message).

You can try using the latest version of the go client library (minio-go), I've just pushed this to the branch `debug-s3-connections`. Please report back :)

**Comment by TamalSaha** [comment]
Still no luck. I get the same error with the updated minio lib:

```
$ ./restic -r s3:s3.amazonaws.com/tigerworks1 backup ~/go/src/github.com/appscode-ci/
enter password for repository: 
scan [/home/tamal/go/src/github.com/appscode-ci]
scanned 569 directories, 2579 files in 0:00
panic: client.PutObject: Put https://tigerworks1.s3-us-west-2.amazonaws.com/restic/data/2abce93135dca9773debc18a5d9650f682957d775eea496fdc16d5835de561e1: dial tcp: lookup tigerworks1.s3-us-west-2.amazonaws.com on 127.0.1.1:53: read udp 127.0.0.1:44816->127.0.1.1:53: i/o timeout

goroutine 2136 [running]:
restic/archiver.(*Archiver).saveChunk(0xc420254af0, 0x1c5c568, 0x2a12ef, 0xb528f52700000, 0xc427d7e000, 0x2a12ef, 0x302000, 0xc4200c02c0, 0xb48080, 0xc420308068, ...)
	/tmp/restic-build-520835754/src/restic/archiver/archiver.go:163 +0x270
created by restic/archiver.(*Archiver).SaveFile
	/tmp/restic-build-520835754/src/restic/archiver/archiver.go:237 +0x381
```

**Comment by fd0** [comment]
Hm, thanks for trying. Can you describe the setup on your local machine in a bit more detail? Specifically:
 * What's your OS and architecture?
 * Are you running restic directly on you OS? Or in a Docker container or VM?
 * Do you use WiFi, or ethernet via cable?

**Comment by TamalSaha** [comment]
> What's your OS and architecture?
Ubuntu 16.04, 64-bit

> Are you running restic directly on you OS? Or in a Docker container or VM?
I use it directly.

> Do you use WiFi, or ethernet via cable?
I am connected via ethernet cable.

I am trying to upload files in this archive https://storage.googleapis.com/restic/cibox.zip. I doubt there is anything special about it.

**Comment by fd0** [comment]
Can you please paste the output of:
 * `cat /etc/resolv.conf`
 * `netstat -tulpen | grep :53`

**Comment by TamalSaha** [comment]
I am bit surprised that dnsmasq is running. 

```
nobody    1418  0.0  0.0  52876  2200 ?        S    Mar14   0:09 /usr/sbin/dnsmasq --no-resolv --keep-in-foreground --no-hosts --bind-interfaces --pid-file=/var/run/NetworkManager/dnsmasq.pid --listen-address=127.0.1.1 --cache-size=0 --conf-file=/dev/null --proxy-dnssec --enable-dbus=org.freedesktop.NetworkManager.dnsmasq --conf-dir=/etc/NetworkManager/dnsmasq.d
```

**Comment by TamalSaha** [comment]
I disabled dnsmasq following the instructions here: http://unix.stackexchange.com/a/304129

Now, I get a new error with debug-s3-connections:
```
$ ./restic -r s3:s3.amazonaws.com/tigerworks1 backup ~/go/src/github.com/appscode-ci/
enter password for repository: 
scan [/home/tamal/go/src/github.com/appscode-ci]
scanned 5381 directories, 42282 files in 0:00
panic: client.PutObject: Put https://tigerworks1.s3-us-west-2.amazonaws.com/restic/data/4506cb4c5f28ab340787d0a3d7967e5ea4b6a2229ac87ac4f074052356807b56: read tcp 192.168.0.100:48292->54.231.184.249:443: read: connection reset by peer

goroutine 2389 [running]:
restic/archiver.(*Archiver).saveChunk(0xc4202cb4f0, 0xc9bab9, 0x36450f, 0x121733b1800000, 0xc4271a2000, 0x36450f, 0x3c8000, 0xc420320000, 0xb48080, 0xc4225c8010, ...)
	/tmp/restic-build-520835754/src/restic/archiver/archiver.go:163 +0x270
created by restic/archiver.(*Archiver).SaveFile
	/tmp/restic-build-520835754/src/restic/archiver/archiver.go:237 +0x381
```

Then tried with the master branch:
```
$ ./restic -r s3:s3.amazonaws.com/tigerworks1 backup ~/go/src/github.com/appscode-ci/
enter password for repository: 
scan [/home/tamal/go/src/github.com/appscode-ci]
scanned 5381 directories, 42282 files in 0:00
panic: client.PutObject: Put https://tigerworks1.s3-us-west-2.amazonaws.com/restic/data/91a38b1163c7c12531306eccd7e10ead4c16638be32fe0ee1e125e3d7826937a: dial tcp: lookup tigerworks1.s3-us-west-2.amazonaws.com on 8.8.8.8:53: read udp 192.168.0.100:39191->8.8.8.8:53: i/o timeout

goroutine 1588 [running]:
restic/archiver.(*Archiver).saveChunk(0xc420255180, 0x1624dd1, 0x1b7fa0, 0x13c9e3d8400000, 0xc42307c000, 0x1b7fa0, 0x1ea000, 0xc4200cc2c0, 0xb3c040, 0xc42000c120, ...)
	/tmp/restic-build-278875416/src/restic/archiver/archiver.go:163 +0x270
created by restic/archiver.(*Archiver).SaveFile
	/tmp/restic-build-278875416/src/restic/archiver/archiver.go:237 +0x381
```

**Comment by fd0** [comment]
This is all very strange, I don't have any leads on how to debug this further. Do you have any idea?

**Comment by TamalSaha** [comment]
:( I don't know. I will try a different computer from the same network and report back.

**Comment by shabbyrobe** [comment]
I get the same issue with my regular DNS and with 8.8.8.8:

```
scanned 377 directories, 17203 files in 0:00
panic: client.PutObject: Put https://...: dial tcp: lookup s3-ap-southeast-2.amazonaws.com on 8.8.8.8:53: read udp 192.168.111.100:41324->8.8.8.8:53: i/o timeout
goroutine 317 [running]:
restic/archiver.(*Archiver).saveChunk(0xc42034c280, 0x280960, 0x39e269, 0xe48affba00000, 0xc42614c000, 0x39e269, 0x3c4000, 0xc4225f6000, 0xb39040, 0xc42000c050, ...)                                                 /tmp/restic-build-913727173/src/restic/archiver/archiver.go:163 +0x270
created by restic/archiver.(*Archiver).SaveFile
        /tmp/restic-build-913727173/src/restic/archiver/archiver.go:237 +0x381
```

Restic appears to upload 108 MB far faster than my 1.5mbit connection could ever allow, then stalls until the above panic:

```
[0:08] 0.42%  13.613 MiB/s  108.908 MiB / 25.605 GiB  93 / 17580 items  0 errors  ETA 31:57
```

**Comment by fd0** [comment]
Hm, that's very very strange. I'll need to borrow a Laptop with Ubuntu 16.04 and test it myself.

**Comment by fd0** [comment]
Btw, what restic displays is not the upload speed and uploaded bytes, but the read speed and read bytes. It starts with reading data, deduplicates it, and builds new pack files (in `/tmp/`). It does that for about 100MB, and only then starts uploading the data.

**Comment by fd0** [comment]
Is the s3 bucket configured in a special way? What's the region used?

**Comment by TamalSaha** [comment]
@fd0, I was using a bucket in Oregon region. There was nothing special about the bucket.

**Comment by fd0** [comment]
I have a wild guess: Could you please apply the following patch, recompile restic and try again? https://gist.github.com/fd0/79970b806ea015136d02fce23852c2ab

**Comment by TamalSaha** [comment]
No luck :(

```
$ ./restic -r s3:s3.amazonaws.com/tigerworks1 backup ~/go/src/github.com/appscode-ci/
enter password for repository: 
scan [/home/tamal/go/src/github.com/appscode-ci]
scanned 5381 directories, 42299 files in 0:02
panic: client.PutObject: Put https://tigerworks1.s3-us-west-2.amazonaws.com/restic/data/2f0223bbf27c2b3cd6404321a17cf1b6c662df104661ea56b1635700661d8c13: dial tcp: lookup tigerworks1.s3-us-west-2.amazonaws.com on 8.8.8.8:53: read udp 192.168.0.100:40296->8.8.8.8:53: i/o timeout

goroutine 2427 [running]:
restic/archiver.(*Archiver).saveChunk(0xc4202dfea0, 0xfcf2cb, 0x168634, 0x1829687ff00000, 0xc42fbbc000, 0x168634, 0x18a000, 0xc4200c02c0, 0xb4b360, 0xc420554168, ...)
	/tmp/restic-build-304550501/src/restic/archiver/archiver.go:163 +0x270
created by restic/archiver.(*Archiver).SaveFile
	/tmp/restic-build-304550501/src/restic/archiver/archiver.go:237 +0x381

$ file ./restic 
./restic: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, stripped
```

**Comment by TamalSaha** [comment]
I just noticed something interesting. If I change the connection limit to 10 from 40, it seems to proceed much further. Then I get the same error.

```
$ ./restic -r s3:s3.amazonaws.com/tigerworks1 backup ~/go/src/github.com/appscode-ci/
enter password for repository: 
scan [/home/tamal/go/src/github.com/appscode-ci]
scanned 5381 directories, 42299 files in 0:01
panic: client.PutObject: Put https://tigerworks1.s3-us-west-2.amazonaws.com/restic/data/58028c127f14a9d39f76fef7fbff4d50116573b9d928b8e5e7fd94a9380de195: dial tcp: lookup tigerworks1.s3-us-west-2.amazonaws.com on 8.8.8.8:53: read udp 192.168.0.100:32881->8.8.8.8:53: i/o timeout

goroutine 2931 [running]:
restic/archiver.(*Archiver).saveChunk(0xc4201d28c0, 0x27ad18, 0x4abb2e, 0x1fa4297a300000, 0xc43b630000, 0x4abb2e, 0x4b6000, 0xc42032b130, 0xb3c040, 0xc4201cc160, ...)
	/tmp/restic-build-387372794/src/restic/archiver/archiver.go:163 +0x270
created by restic/archiver.(*Archiver).SaveFile
	/tmp/restic-build-387372794/src/restic/archiver/archiver.go:237 +0x381
panic: client.PutObject: Put https://tigerworks1.s3-us-west-2.amazonaws.com/restic/data/7a79b27da9c56a442f9ed913d3c01124ff1035aa228d0cd1fcb9f3ee2c8d40c8: dial tcp: lookup tigerworks1.s3-us-west-2.amazonaws.com on 8.8.8.8:53: read udp 192.168.0.100:32881->8.8.8.8:53: i/o timeout

goroutine 2919 [running]:
restic/archiver.(*Archiver).saveChunk(0xc4201d28c0, 0x20ec031, 0x24cdf9, 0x1bac7bf3200000, 0xc42c6c6000, 0x24cdf9, 0x26a000, 0xc42032b130, 0xb3c040, 0xc4205ba1c0, ...)
	/tmp/restic-build-387372794/src/restic/archiver/archiver.go:163 +0x270
created by restic/archiver.(*Archiver).SaveFile
	/tmp/restic-build-387372794/src/restic/archiver/archiver.go:237 +0x381
panic: client.PutObject: Put https://tigerworks1.s3-us-west-2.amazonaws.com/restic/data/da38701456f9d395ec9e4e842487eb8992d71a5df01ad4c9b6e092d551c84226: dial tcp: lookup tigerworks1.s3-us-west-2.amazonaws.com on 8.8.8.8:53: read udp 192.168.0.100:32881->8.8.8.8:53: i/o timeout

goroutine 2859 [running]:
restic/archiver.(*Archiver).saveChunk(0xc4201d28c0, 0xafaa46, 0x26f1c2, 0x1a4c5d28f00000, 0xc421158000, 0x26f1c2, 0x302000, 0xc42032b130, 0xb3c040, 0xc4202ea000, ...)
	/tmp/restic-build-387372794/src/restic/archiver/archiver.go:163 +0x270
created by restic/archiver.(*Archiver).SaveFile
	/tmp/restic-build-387372794/src/restic/archiver/archiver.go:237 +0x381
```

**Comment by TamalSaha** [comment]
Finally got a working run. I set the connection limit to 2

```
$ ./restic -r s3:s3.amazonaws.com/tigerworks1 backup ~/go/src/github.com/appscode-ci/
enter password for repository: 
scan [/home/tamal/go/src/github.com/appscode-ci]
scanned 5381 directories, 42299 files in 0:02
[20:11] 100.00%  1.515 MiB/s  1.791 GiB / 1.791 GiB  47680 / 47680 items  0 errors  ETA 0:00 
duration: 20:11, 1.51MiB/s
snapshot cbb5f6f1 saved
```
The interesting thing here is that the BW matches my upload bandwidth.

**Comment by fd0** [comment]
Huh, very strange indeed. Is there some kind of connection limit enforced by either the OS or the router/cable modem?

**Comment by TamalSaha** [comment]
> Is there some kind of connection limit enforced by either the OS or the router/cable modem?

I did not do anything non-default. Is there any command I can run to check/compare?

**Comment by shabbyrobe** [comment]
@TamilSaha, how did you set the connection limit? By modifying the source or is there a flag?

**Comment by fd0** [comment]
@shabbyrobe you need to change the source, here: https://github.com/restic/restic/blob/master/src/restic/backend/s3/s3.go#L20

**Comment by shabbyrobe** [comment]
Yep, sorry, I ended up working it out. Didn't change anything for me though unfortunately, still get the same timeout.

**Comment by shabbyrobe** [comment]
I tried getting DNS out of the equation by adding this to my `/etc/hosts`:

> 52.95.131.45 s3-ap-southeast-2.amazonaws.com

Unfortunately, it didn't stop the problem, only changed the error. The output was pretty much the same up until the panic:
```
panic: client.PutObject: Put https://s3-ap-southeast-2.amazonaws.com/...: read tcp 192.168.111.100:43888->52.95.131.
45:443: read: connection reset by peer
```

**Comment by TamalSaha** [comment]
@shabbyrobe how many connections did you use?

To me this seems like a throttling issue. Either DNS provider or cloud provider (S3) starts throttling when there are too many parallel operations from same IP.

**Comment by TamalSaha** [comment]
I did some more tests using some VMs in DigitalOcean to check if my local network some kind of issue. This is what I have found.

## VM 1: Debian 8.7, using the official restic 0.5 binary
There was no issue. Everything went fine on first try.
```
# ./restic -r s3:s3.amazonaws.com/tigerworks1 backup ~/dockerfiles
enter password for repository: 
scan [/root/dockerfiles]
scanned 22049 directories, 147904 files in 0:05
[2:52] 100.00%  19.487 MiB/s  3.273 GiB / 3.273 GiB  169953 / 169953 items  0 errors  ETA 0:00 
duration: 2:52, 19.42MiB/s
snapshot d336c1e8 saved
```

## VM 1: Ubuntu 16.04.2
**Using official restic 0.5 binary**
I get segfault when I try to init repo
```
# ./restic -r s3:s3.amazonaws.com/tigerworks1/t11 init
Segmentation fault (core dumped)
```
I tried running with valgrind. This is what I see:
```
--2837-- WARNING: unhandled amd64-linux syscall: 329
==2837==    at 0x4547FD: ??? (in /root/restic)
==2837==    by 0x450780: ??? (in /root/restic)
--2837-- You may be able to write your own handler.
--2837-- Read the file README_MISSING_SYSCALL_OR_IOCTL.
--2837-- Nevertheless we consider this a bug.  Please report
--2837-- it at http://valgrind.org/support/bug_reports.html.
==2837== Invalid write of size 8
==2837==    at 0x450781: ??? (in /root/restic)
==2837==  Address 0xfffffffffffffff8 is not stack'd, malloc'd or (recently) free'd
```

**New static binary compiled on Ubuntu 16.04**
```
enter password for repository: 
scan [/root/testdata]
scanned 536 directories, 2538 files in 0:02
panic: client.PutObject: Put https://tigerworks1.s3-us-west-2.amazonaws.com/t11/data/2a752141ebd257084ae76e36a4539600d09f7e7ebf4e88e048d31dcf93be2059: write tcp 104.236.96.207:59772->52.218.144.61:443: write: broken pipe

goroutine 1301 [running]:
restic/archiver.(*Archiver).saveChunk(0xc420366be0, 0x1f224f4, 0x180b98, 0x465946cd00000, 0xc428c2a000, 0x180b98, 0x188000, 0xc420098370, 0xb3c040, 0xc42000c170, ...)
	/tmp/restic-build-877612307/src/restic/archiver/archiver.go:163 +0x270
created by restic/archiver.(*Archiver).SaveFile
	/tmp/restic-build-877612307/src/restic/archiver/archiver.go:237 +0x381
```

**New static binary compiled on Ubuntu 16.04 using CGO patch**
Now init worked. But `backup` operation gets `killed`. I tried with valgrind, did not see anything note worthy.
```
enter password for repository: 
scan [/root/testdata]
scanned 536 directories, 2538 files in 0:01
Killed 7.28%  303.521 KiB/s  74.102 MiB / 1017.891 MiB  2179 / 3074 items  0 errors  ETA 53:04 
```

**Comment by fd0** [comment]
Huh, the second case on "VM 2: Ubuntu 16.04.2" with the segfault bothers me. Can you please run `file` on the file and check that it is really for the correct OS?

**Comment by fd0** [comment]
For example, running the binaries for FreeBSD/OpenBSD (386/amd64) on Linux will lead to an instant segfault.

**Comment by TamalSaha** [comment]
I think I made a mistake with "VM 2: Ubuntu 16.04.2" example using official restic 0.5 binary. I rerun. It worked this time. Sorry about the false alert.

```
# ./restic -r s3:s3.amazonaws.com/tigerworks1/t50 backup ~/cibox
enter password for repository: 
scan [/root/cibox]
scanned 535 directories, 2537 files in 0:00
[0:17] 100.00%  30.578 MiB/s  519.824 MiB / 519.824 MiB  3072 / 3072 items  0 errors  ETA 0:00 
duration: 0:17, 30.39MiB/s
snapshot 4e65552f saved
```

**Comment by fd0** [comment]
So, where does this leave us? Strange errors on Ubuntu 16.04 Desktop on your home networks, on the servers it works, just one disconnecT?

**Comment by TamalSaha** [comment]
> Strange errors on Ubuntu 16.04 Desktop on your home networks, on the servers it works, just one disconnect?

Yes. Seems that way. Either S3 or my ISP (comcast) has some kind of throttling on uploads, I think.

**Comment by shabbyrobe** [comment]
> Strange errors on Ubuntu 16.04 Desktop on your home networks

Yep, is there anything else I can do to help debug? Wireshark?

**Comment by fd0** [comment]
Hm, you can try. Maybe you'll see something...

**Comment by fd0** [comment]
I just ran into the resolve issues, lowering the number of concurrent connections to s3 (from 40 to 10) made it much better. I'll merge this change (#918) into master soon so you can check if it works for you.

**Comment by fd0** [comment]
It's merged, could you please have a look?

**Comment by fd0** [comment]
Since there was no feedback for several weeks I'm going to close this issue for now. Let us know if it persists.

**Comment by jazoom** [comment]
It seems I had the same issue just now, running `restic restore` within a Docker container. It worked fine with Docker for Windows but had the DNS issue on Debian 9. I got it to work by adding `--network host` to the `docker run` command.

**Comment by fd0** [comment]
@jazoom which version  of restic was that?

**Comment by jazoom** [comment]
@fd0 
```
docker run --rm -v /local/dir:/backup -e RESTIC_PASSWORD=restic-password -e RESTIC_REPOSITORY=s3:s3-eu-west-1.amazonaws.com/bucket-name -e AWS_ACCESS_KEY_ID=key-id -e AWS_SECRET_ACCESS_KEY=secret restic/restic:0.9.2 restore latest --verbose=2 --target=.
```
